In [143]:
import pandas as pd
import numpy as np

In [144]:
df = pd.read_csv(r'C:\Users\Junayed\pandas_prac\Aug_1\Gym\messy_gym_aug1b.csv')

In [145]:
df

,MemberID,Name,Age,Height,Weight,MembershipType,MonthlyFee,JoinDate,Email,Status,Notes
0,G001,Ahsan Reza,29.0,175cm,70kg,Premium,$49.99,2023-02-01,ahsan.reza@gmail.com,active,NaN
1,G002,Meera Nair,34.0,5.6ft,132lbs,premium,49.99,02/03/2023,meera.nair@gmail.com,Active,NaN
2,G003,Tomasz Kowalski,41.0,180cm,NaN,Basic,$19.99,2023-02-05,tomasz.k@,ACTIVE,No email domain
3,G004,NaN,150.0,168cm,60kg,VIP,$99.99,05-02-2023,jenny_oconnor@yahoo.com,active,Age typo?
4,G005,Carlos Mendes,25.0,NaN,82kg,Basc,$19.99,2023-02-08,carlos.mendes@hotmail.com,inactive,Typo in plan
5,G006,Aiko Sato,31.0,162cm,54kg,Premium,NaN,2023-02-10,aiko.sato@gmail.com,Active,Missing fee
6,G007,Ben Turner,-5.0,178cm,75kg,Basic,$19.99,10/02/2023,ben.turner@gmail.com,active,Negative age
7,G008,Ravi Chandran,45.0,171cm,68kg,Premeium,$49.99,2023-02-12,ravi.chandran@gmail.com,Inactive,Typo in plan
8,G009,Ravi Chandran,45.0,171cm,68kg,Premium,$49.99,2023-02-12,ravi.chandran@gmail.com,inactive,Possible duplicate
9,G010,Nadia Popescu,NaN,158cm,50kg,VIP,$99.99,12-02-2023,nadia.popescu@gmail.com,active,Missing age
10,G011,Diego Fernandez,38.0,183cm,90kg,basic,$19.99,2023-02-14,diego.fernandez,active,Bad email format
11,G012,Lin Chen,27.0,165cm,58kg,Premium,$49.99,2023-02-15,lin.chen@gmail.com,active,NaN
12,G013,Grace Osei,52.0,160cm,NaN,VIP,$99.99,15/02/2023,grace.osei@gmail.com,ACTIVE,NaN
13,G014,Omar Farouk,NaN,177cm,80kg,Basic,$19.99,2023-02-17,omar.farouk@gmail.com,active,VIP trial
14,G015,Sara Kim,33.0,5.4ft,120lbs,Premium,$49.99,2023-02-18,sara.kim@gmail.com,Active,NaN
15,G016,Jonas Weber,29.0,182cm,88kg,VIP,$0.00,2023-02-19,jonas.weber@gmail.com,inactive,Fee looks wrong
16,G017,Priya Iyer,36.0,NaN,63kg,Basic,$19.99,19-02-2023,priya.iyer@gmail.com,active,NaN
17,G018,Michael Brown,300.0,174cm,79kg,Premium,$49.99,2023-02-21,michael.brown@gmail.com,active,Age outlier
18,G019,Elena Rossi,24.0,170cm,NaN,basic,$19.99,2023-02-22,elena.rossi@gmail.com,ACTIVE,NaN
19,G020,Elena Rossi,24.0,170cm,55kg,Basic,$19.99,2023-02-22,elena.rossi@gmail.com,active,Duplicate?

In [146]:
print('Shape:', df.shape)

Shape: (20, 11)

In [147]:
df.dtypes

MemberID              str
Name                  str
Age               float64
Height                str
Weight                str
MembershipType        str
MonthlyFee            str
JoinDate              str
Email                 str
Status                str
Notes                 str
dtype: object

In [148]:
df.isna().sum()

MemberID          0
Name              1
Age               2
Height            2
Weight            3
MembershipType    0
MonthlyFee        1
JoinDate          0
Email             0
Status            0
Notes             7
dtype: int64

In [149]:
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

df.loc[(df['Age'] < 10) | (df['Age'] > 100), 'Age'] = np.nan

df['Age']

0     29.0
1     34.0
2     41.0
3      NaN
4     25.0
5     31.0
6      NaN
7     45.0
8     45.0
9      NaN
10    38.0
11    27.0
12    52.0
13     NaN
14    33.0
15    29.0
16    36.0
17     NaN
18    24.0
19    24.0
Name: Age, dtype: float64

In [150]:
df

,MemberID,Name,Age,Height,Weight,MembershipType,MonthlyFee,JoinDate,Email,Status,Notes
0,G001,Ahsan Reza,29.0,175cm,70kg,Premium,$49.99,2023-02-01,ahsan.reza@gmail.com,active,NaN
1,G002,Meera Nair,34.0,5.6ft,132lbs,premium,49.99,02/03/2023,meera.nair@gmail.com,Active,NaN
2,G003,Tomasz Kowalski,41.0,180cm,NaN,Basic,$19.99,2023-02-05,tomasz.k@,ACTIVE,No email domain
3,G004,NaN,NaN,168cm,60kg,VIP,$99.99,05-02-2023,jenny_oconnor@yahoo.com,active,Age typo?
4,G005,Carlos Mendes,25.0,NaN,82kg,Basc,$19.99,2023-02-08,carlos.mendes@hotmail.com,inactive,Typo in plan
5,G006,Aiko Sato,31.0,162cm,54kg,Premium,NaN,2023-02-10,aiko.sato@gmail.com,Active,Missing fee
6,G007,Ben Turner,NaN,178cm,75kg,Basic,$19.99,10/02/2023,ben.turner@gmail.com,active,Negative age
7,G008,Ravi Chandran,45.0,171cm,68kg,Premeium,$49.99,2023-02-12,ravi.chandran@gmail.com,Inactive,Typo in plan
8,G009,Ravi Chandran,45.0,171cm,68kg,Premium,$49.99,2023-02-12,ravi.chandran@gmail.com,inactive,Possible duplicate
9,G010,Nadia Popescu,NaN,158cm,50kg,VIP,$99.99,12-02-2023,nadia.popescu@gmail.com,active,Missing age
10,G011,Diego Fernandez,38.0,183cm,90kg,basic,$19.99,2023-02-14,diego.fernandez,active,Bad email format
11,G012,Lin Chen,27.0,165cm,58kg,Premium,$49.99,2023-02-15,lin.chen@gmail.com,active,NaN
12,G013,Grace Osei,52.0,160cm,NaN,VIP,$99.99,15/02/2023,grace.osei@gmail.com,ACTIVE,NaN
13,G014,Omar Farouk,NaN,177cm,80kg,Basic,$19.99,2023-02-17,omar.farouk@gmail.com,active,VIP trial
14,G015,Sara Kim,33.0,5.4ft,120lbs,Premium,$49.99,2023-02-18,sara.kim@gmail.com,Active,NaN
15,G016,Jonas Weber,29.0,182cm,88kg,VIP,$0.00,2023-02-19,jonas.weber@gmail.com,inactive,Fee looks wrong
16,G017,Priya Iyer,36.0,NaN,63kg,Basic,$19.99,19-02-2023,priya.iyer@gmail.com,active,NaN
17,G018,Michael Brown,NaN,174cm,79kg,Premium,$49.99,2023-02-21,michael.brown@gmail.com,active,Age outlier
18,G019,Elena Rossi,24.0,170cm,NaN,basic,$19.99,2023-02-22,elena.rossi@gmail.com,ACTIVE,NaN
19,G020,Elena Rossi,24.0,170cm,55kg,Basic,$19.99,2023-02-22,elena.rossi@gmail.com,active,Duplicate?

In [151]:
def height_to_cm(val):
    if pd.isna(val):
        return np.nan
    val = str(val).strip().lower()
    if val.endswith("cm"):
        return float(val.replace("cm",""))
    if val.endswith("ft"):
        num = float(val.replace("ft",""))
        feet = int(num)
        inches = round((num - feet ) * 10)
        return round(feet* 30.48 + inches * 2.54, 1)
    return np.nan

df["Height_cm"] = df["Height"].apply(height_to_cm)

df[['Height', 'Height_cm']]

   Height  Height_cm
0   175cm      175.0
1   5.6ft      167.6
2   180cm      180.0
3   168cm      168.0
4     NaN        NaN
5   162cm      162.0
6   178cm      178.0
7   171cm      171.0
8   171cm      171.0
9   158cm      158.0
10  183cm      183.0
11  165cm      165.0
12  160cm      160.0
13  177cm      177.0
14  5.4ft      162.6
15  182cm      182.0
16    NaN        NaN
17  174cm      174.0
18  170cm      170.0
19  170cm      170.0

In [152]:
df['Height'] = df['Height_cm']
df = df.drop(columns=['Height_cm'])

In [153]:
def weight_to_kg(val):
    if pd.isna(val):
        return np.nan

    val = str(val).strip().lower()

    if val.endswith("kg"):
        return float(val.replace("kg",""))

    if val.endswith("lbs"):
        return round(float(val.replace("lbs","")) * 0.453592, 1)
    return np.nan

df['Weight_kg'] = df['Weight'].apply(weight_to_kg)
df[['Weight', 'Weight_kg']]

    Weight  Weight_kg
0     70kg       70.0
1   132lbs       59.9
2      NaN        NaN
3     60kg       60.0
4     82kg       82.0
5     54kg       54.0
6     75kg       75.0
7     68kg       68.0
8     68kg       68.0
9     50kg       50.0
10    90kg       90.0
11    58kg       58.0
12     NaN        NaN
13    80kg       80.0
14  120lbs       54.4
15    88kg       88.0
16    63kg       63.0
17    79kg       79.0
18     NaN        NaN
19    55kg       55.0

In [154]:
df['Weight'] = df['Weight_kg']

df = df.drop(columns = 'Weight_kg')

In [155]:
df

,MemberID,Name,Age,Height,Weight,MembershipType,MonthlyFee,JoinDate,Email,Status,Notes
0,G001,Ahsan Reza,29.0,175.0,70.0,Premium,$49.99,2023-02-01,ahsan.reza@gmail.com,active,NaN
1,G002,Meera Nair,34.0,167.6,59.9,premium,49.99,02/03/2023,meera.nair@gmail.com,Active,NaN
2,G003,Tomasz Kowalski,41.0,180.0,NaN,Basic,$19.99,2023-02-05,tomasz.k@,ACTIVE,No email domain
3,G004,NaN,NaN,168.0,60.0,VIP,$99.99,05-02-2023,jenny_oconnor@yahoo.com,active,Age typo?
4,G005,Carlos Mendes,25.0,NaN,82.0,Basc,$19.99,2023-02-08,carlos.mendes@hotmail.com,inactive,Typo in plan
5,G006,Aiko Sato,31.0,162.0,54.0,Premium,NaN,2023-02-10,aiko.sato@gmail.com,Active,Missing fee
6,G007,Ben Turner,NaN,178.0,75.0,Basic,$19.99,10/02/2023,ben.turner@gmail.com,active,Negative age
7,G008,Ravi Chandran,45.0,171.0,68.0,Premeium,$49.99,2023-02-12,ravi.chandran@gmail.com,Inactive,Typo in plan
8,G009,Ravi Chandran,45.0,171.0,68.0,Premium,$49.99,2023-02-12,ravi.chandran@gmail.com,inactive,Possible duplicate
9,G010,Nadia Popescu,NaN,158.0,50.0,VIP,$99.99,12-02-2023,nadia.popescu@gmail.com,active,Missing age
10,G011,Diego Fernandez,38.0,183.0,90.0,basic,$19.99,2023-02-14,diego.fernandez,active,Bad email format
11,G012,Lin Chen,27.0,165.0,58.0,Premium,$49.99,2023-02-15,lin.chen@gmail.com,active,NaN
12,G013,Grace Osei,52.0,160.0,NaN,VIP,$99.99,15/02/2023,grace.osei@gmail.com,ACTIVE,NaN
13,G014,Omar Farouk,NaN,177.0,80.0,Basic,$19.99,2023-02-17,omar.farouk@gmail.com,active,VIP trial
14,G015,Sara Kim,33.0,162.6,54.4,Premium,$49.99,2023-02-18,sara.kim@gmail.com,Active,NaN
15,G016,Jonas Weber,29.0,182.0,88.0,VIP,$0.00,2023-02-19,jonas.weber@gmail.com,inactive,Fee looks wrong
16,G017,Priya Iyer,36.0,NaN,63.0,Basic,$19.99,19-02-2023,priya.iyer@gmail.com,active,NaN
17,G018,Michael Brown,NaN,174.0,79.0,Premium,$49.99,2023-02-21,michael.brown@gmail.com,active,Age outlier
18,G019,Elena Rossi,24.0,170.0,NaN,basic,$19.99,2023-02-22,elena.rossi@gmail.com,ACTIVE,NaN
19,G020,Elena Rossi,24.0,170.0,55.0,Basic,$19.99,2023-02-22,elena.rossi@gmail.com,active,Duplicate?

In [156]:
type_map = {
    "premium": "Premium", "premeium": "Premium",
    "basic": "Basic", "basc": "Basic",
    "vip": "VIP",
}
df["MembershipType"] = df["MembershipType"].str.strip().str.lower().map(type_map)
df["MembershipType"].value_counts()

MembershipType
Premium    8
Basic      8
VIP        4
Name: count, dtype: int64

In [157]:
df['MembershipType']

0     Premium
1     Premium
2       Basic
3         VIP
4       Basic
5     Premium
6       Basic
7     Premium
8     Premium
9         VIP
10      Basic
11    Premium
12        VIP
13      Basic
14    Premium
15        VIP
16      Basic
17    Premium
18      Basic
19      Basic
Name: MembershipType, dtype: str

In [158]:
df

,MemberID,Name,Age,Height,Weight,MembershipType,MonthlyFee,JoinDate,Email,Status,Notes
0,G001,Ahsan Reza,29.0,175.0,70.0,Premium,$49.99,2023-02-01,ahsan.reza@gmail.com,active,NaN
1,G002,Meera Nair,34.0,167.6,59.9,Premium,49.99,02/03/2023,meera.nair@gmail.com,Active,NaN
2,G003,Tomasz Kowalski,41.0,180.0,NaN,Basic,$19.99,2023-02-05,tomasz.k@,ACTIVE,No email domain
3,G004,NaN,NaN,168.0,60.0,VIP,$99.99,05-02-2023,jenny_oconnor@yahoo.com,active,Age typo?
4,G005,Carlos Mendes,25.0,NaN,82.0,Basic,$19.99,2023-02-08,carlos.mendes@hotmail.com,inactive,Typo in plan
5,G006,Aiko Sato,31.0,162.0,54.0,Premium,NaN,2023-02-10,aiko.sato@gmail.com,Active,Missing fee
6,G007,Ben Turner,NaN,178.0,75.0,Basic,$19.99,10/02/2023,ben.turner@gmail.com,active,Negative age
7,G008,Ravi Chandran,45.0,171.0,68.0,Premium,$49.99,2023-02-12,ravi.chandran@gmail.com,Inactive,Typo in plan
8,G009,Ravi Chandran,45.0,171.0,68.0,Premium,$49.99,2023-02-12,ravi.chandran@gmail.com,inactive,Possible duplicate
9,G010,Nadia Popescu,NaN,158.0,50.0,VIP,$99.99,12-02-2023,nadia.popescu@gmail.com,active,Missing age
10,G011,Diego Fernandez,38.0,183.0,90.0,Basic,$19.99,2023-02-14,diego.fernandez,active,Bad email format
11,G012,Lin Chen,27.0,165.0,58.0,Premium,$49.99,2023-02-15,lin.chen@gmail.com,active,NaN
12,G013,Grace Osei,52.0,160.0,NaN,VIP,$99.99,15/02/2023,grace.osei@gmail.com,ACTIVE,NaN
13,G014,Omar Farouk,NaN,177.0,80.0,Basic,$19.99,2023-02-17,omar.farouk@gmail.com,active,VIP trial
14,G015,Sara Kim,33.0,162.6,54.4,Premium,$49.99,2023-02-18,sara.kim@gmail.com,Active,NaN
15,G016,Jonas Weber,29.0,182.0,88.0,VIP,$0.00,2023-02-19,jonas.weber@gmail.com,inactive,Fee looks wrong
16,G017,Priya Iyer,36.0,NaN,63.0,Basic,$19.99,19-02-2023,priya.iyer@gmail.com,active,NaN
17,G018,Michael Brown,NaN,174.0,79.0,Premium,$49.99,2023-02-21,michael.brown@gmail.com,active,Age outlier
18,G019,Elena Rossi,24.0,170.0,NaN,Basic,$19.99,2023-02-22,elena.rossi@gmail.com,ACTIVE,NaN
19,G020,Elena Rossi,24.0,170.0,55.0,Basic,$19.99,2023-02-22,elena.rossi@gmail.com,active,Duplicate?

In [159]:
df["MonthlyFee"] = pd.to_numeric(df["MonthlyFee"].astype(str).str.replace("$","", regex=False).str.strip(), errors='coerce')

df["MonthlyFee"]

0     49.99
1     49.99
2     19.99
3     99.99
4     19.99
5       NaN
6     19.99
7     49.99
8     49.99
9     99.99
10    19.99
11    49.99
12    99.99
13    19.99
14    49.99
15     0.00
16    19.99
17    49.99
18    19.99
19    19.99
Name: MonthlyFee, dtype: float64

In [160]:
df["JoinDate"] = pd.to_datetime(df["JoinDate"], format= 'mixed', dayfirst=False)

df["JoinDate"]

0    2023-02-01
1    2023-02-03
2    2023-02-05
3    2023-05-02
4    2023-02-08
5    2023-02-10
6    2023-10-02
7    2023-02-12
8    2023-02-12
9    2023-12-02
10   2023-02-14
11   2023-02-15
12   2023-02-15
13   2023-02-17
14   2023-02-18
15   2023-02-19
16   2023-02-19
17   2023-02-21
18   2023-02-22
19   2023-02-22
Name: JoinDate, dtype: datetime64[us]

In [161]:
df["Status"] = df["Status"].str.title()

df["Status"]

0       Active
1       Active
2       Active
3       Active
4     Inactive
5       Active
6       Active
7     Inactive
8     Inactive
9       Active
10      Active
11      Active
12      Active
13      Active
14      Active
15    Inactive
16      Active
17      Active
18      Active
19      Active
Name: Status, dtype: str

In [162]:
df["EmailValid"] = df["Email"].astype(str).str.match(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")

df['Emails'] = df['Email'].where(df['EmailValid'], np.nan)
df[["Email", "EmailValid", "Emails"]]

                        Email  EmailValid                     Emails
0        ahsan.reza@gmail.com        True       ahsan.reza@gmail.com
1        meera.nair@gmail.com        True       meera.nair@gmail.com
2                   tomasz.k@       False                        NaN
3     jenny_oconnor@yahoo.com        True    jenny_oconnor@yahoo.com
4   carlos.mendes@hotmail.com        True  carlos.mendes@hotmail.com
5         aiko.sato@gmail.com        True        aiko.sato@gmail.com
6        ben.turner@gmail.com        True       ben.turner@gmail.com
7     ravi.chandran@gmail.com        True    ravi.chandran@gmail.com
8     ravi.chandran@gmail.com        True    ravi.chandran@gmail.com
9     nadia.popescu@gmail.com        True    nadia.popescu@gmail.com
10            diego.fernandez       False                        NaN
11         lin.chen@gmail.com        True         lin.chen@gmail.com
12       grace.osei@gmail.com        True       grace.osei@gmail.com
13      omar.farouk@gmail.com        True      omar.farouk@gmail.com
14         sara.kim@gmail.com        True         sara.kim@gmail.com
15      jonas.weber@gmail.com        True      jonas.weber@gmail.com
16       priya.iyer@gmail.com        True       priya.iyer@gmail.com
17    michael.brown@gmail.com        True    michael.brown@gmail.com
18      elena.rossi@gmail.com        True      elena.rossi@gmail.com
19      elena.rossi@gmail.com        True      elena.rossi@gmail.com

In [163]:
df

,MemberID,Name,Age,Height,Weight,MembershipType,MonthlyFee,JoinDate,Email,Status,Notes,EmailValid,Emails
0,G001,Ahsan Reza,29.0,175.0,70.0,Premium,49.99,2023-02-01,ahsan.reza@gmail.com,Active,NaN,True,ahsan.reza@gmail.com
1,G002,Meera Nair,34.0,167.6,59.9,Premium,49.99,2023-02-03,meera.nair@gmail.com,Active,NaN,True,meera.nair@gmail.com
2,G003,Tomasz Kowalski,41.0,180.0,NaN,Basic,19.99,2023-02-05,tomasz.k@,Active,No email domain,False,NaN
3,G004,NaN,NaN,168.0,60.0,VIP,99.99,2023-05-02,jenny_oconnor@yahoo.com,Active,Age typo?,True,jenny_oconnor@yahoo.com
4,G005,Carlos Mendes,25.0,NaN,82.0,Basic,19.99,2023-02-08,carlos.mendes@hotmail.com,Inactive,Typo in plan,True,carlos.mendes@hotmail.com
5,G006,Aiko Sato,31.0,162.0,54.0,Premium,NaN,2023-02-10,aiko.sato@gmail.com,Active,Missing fee,True,aiko.sato@gmail.com
6,G007,Ben Turner,NaN,178.0,75.0,Basic,19.99,2023-10-02,ben.turner@gmail.com,Active,Negative age,True,ben.turner@gmail.com
7,G008,Ravi Chandran,45.0,171.0,68.0,Premium,49.99,2023-02-12,ravi.chandran@gmail.com,Inactive,Typo in plan,True,ravi.chandran@gmail.com
8,G009,Ravi Chandran,45.0,171.0,68.0,Premium,49.99,2023-02-12,ravi.chandran@gmail.com,Inactive,Possible duplicate,True,ravi.chandran@gmail.com
9,G010,Nadia Popescu,NaN,158.0,50.0,VIP,99.99,2023-12-02,nadia.popescu@gmail.com,Active,Missing age,True,nadia.popescu@gmail.com
10,G011,Diego Fernandez,38.0,183.0,90.0,Basic,19.99,2023-02-14,diego.fernandez,Active,Bad email format,False,NaN
11,G012,Lin Chen,27.0,165.0,58.0,Premium,49.99,2023-02-15,lin.chen@gmail.com,Active,NaN,True,lin.chen@gmail.com
12,G013,Grace Osei,52.0,160.0,NaN,VIP,99.99,2023-02-15,grace.osei@gmail.com,Active,NaN,True,grace.osei@gmail.com
13,G014,Omar Farouk,NaN,177.0,80.0,Basic,19.99,2023-02-17,omar.farouk@gmail.com,Active,VIP trial,True,omar.farouk@gmail.com
14,G015,Sara Kim,33.0,162.6,54.4,Premium,49.99,2023-02-18,sara.kim@gmail.com,Active,NaN,True,sara.kim@gmail.com
15,G016,Jonas Weber,29.0,182.0,88.0,VIP,0.00,2023-02-19,jonas.weber@gmail.com,Inactive,Fee looks wrong,True,jonas.weber@gmail.com
16,G017,Priya Iyer,36.0,NaN,63.0,Basic,19.99,2023-02-19,priya.iyer@gmail.com,Active,NaN,True,priya.iyer@gmail.com
17,G018,Michael Brown,NaN,174.0,79.0,Premium,49.99,2023-02-21,michael.brown@gmail.com,Active,Age outlier,True,michael.brown@gmail.com
18,G019,Elena Rossi,24.0,170.0,NaN,Basic,19.99,2023-02-22,elena.rossi@gmail.com,Active,NaN,True,elena.rossi@gmail.com
19,G020,Elena Rossi,24.0,170.0,55.0,Basic,19.99,2023-02-22,elena.rossi@gmail.com,Active,Duplicate?,True,elena.rossi@gmail.com

In [164]:
df['Email'] = df['Emails']

df = df.drop(columns = 'Emails')

In [165]:
df

,MemberID,Name,Age,Height,Weight,MembershipType,MonthlyFee,JoinDate,Email,Status,Notes,EmailValid
0,G001,Ahsan Reza,29.0,175.0,70.0,Premium,49.99,2023-02-01,ahsan.reza@gmail.com,Active,NaN,True
1,G002,Meera Nair,34.0,167.6,59.9,Premium,49.99,2023-02-03,meera.nair@gmail.com,Active,NaN,True
2,G003,Tomasz Kowalski,41.0,180.0,NaN,Basic,19.99,2023-02-05,NaN,Active,No email domain,False
3,G004,NaN,NaN,168.0,60.0,VIP,99.99,2023-05-02,jenny_oconnor@yahoo.com,Active,Age typo?,True
4,G005,Carlos Mendes,25.0,NaN,82.0,Basic,19.99,2023-02-08,carlos.mendes@hotmail.com,Inactive,Typo in plan,True
5,G006,Aiko Sato,31.0,162.0,54.0,Premium,NaN,2023-02-10,aiko.sato@gmail.com,Active,Missing fee,True
6,G007,Ben Turner,NaN,178.0,75.0,Basic,19.99,2023-10-02,ben.turner@gmail.com,Active,Negative age,True
7,G008,Ravi Chandran,45.0,171.0,68.0,Premium,49.99,2023-02-12,ravi.chandran@gmail.com,Inactive,Typo in plan,True
8,G009,Ravi Chandran,45.0,171.0,68.0,Premium,49.99,2023-02-12,ravi.chandran@gmail.com,Inactive,Possible duplicate,True
9,G010,Nadia Popescu,NaN,158.0,50.0,VIP,99.99,2023-12-02,nadia.popescu@gmail.com,Active,Missing age,True
10,G011,Diego Fernandez,38.0,183.0,90.0,Basic,19.99,2023-02-14,NaN,Active,Bad email format,False
11,G012,Lin Chen,27.0,165.0,58.0,Premium,49.99,2023-02-15,lin.chen@gmail.com,Active,NaN,True
12,G013,Grace Osei,52.0,160.0,NaN,VIP,99.99,2023-02-15,grace.osei@gmail.com,Active,NaN,True
13,G014,Omar Farouk,NaN,177.0,80.0,Basic,19.99,2023-02-17,omar.farouk@gmail.com,Active,VIP trial,True
14,G015,Sara Kim,33.0,162.6,54.4,Premium,49.99,2023-02-18,sara.kim@gmail.com,Active,NaN,True
15,G016,Jonas Weber,29.0,182.0,88.0,VIP,0.00,2023-02-19,jonas.weber@gmail.com,Inactive,Fee looks wrong,True
16,G017,Priya Iyer,36.0,NaN,63.0,Basic,19.99,2023-02-19,priya.iyer@gmail.com,Active,NaN,True
17,G018,Michael Brown,NaN,174.0,79.0,Premium,49.99,2023-02-21,michael.brown@gmail.com,Active,Age outlier,True
18,G019,Elena Rossi,24.0,170.0,NaN,Basic,19.99,2023-02-22,elena.rossi@gmail.com,Active,NaN,True
19,G020,Elena Rossi,24.0,170.0,55.0,Basic,19.99,2023-02-22,elena.rossi@gmail.com,Active,Duplicate?,True

In [166]:
df["Notes"] = df["Notes"].astype(str).str.strip().replace(["nan", "None", ""], np.nan)

df["Notes"]

0                    NaN
1                    NaN
2        No email domain
3              Age typo?
4           Typo in plan
5            Missing fee
6           Negative age
7           Typo in plan
8     Possible duplicate
9            Missing age
10      Bad email format
11                   NaN
12                   NaN
13             VIP trial
14                   NaN
15       Fee looks wrong
16                   NaN
17           Age outlier
18                   NaN
19            Duplicate?
Name: Notes, dtype: str

In [167]:
df = df.drop(columns= 'EmailValid')

In [168]:
check_cols = ["Name", "Age", "MembershipType", "Status", "JoinDate", "Email"]
df[df.duplicated(subset=check_cols, keep=False)]

,MemberID,Name,Age,Height,Weight,MembershipType,MonthlyFee,JoinDate,Email,Status,Notes
7,G008,Ravi Chandran,45.0,171.0,68.0,Premium,49.99,2023-02-12,ravi.chandran@gmail.com,Inactive,Typo in plan
8,G009,Ravi Chandran,45.0,171.0,68.0,Premium,49.99,2023-02-12,ravi.chandran@gmail.com,Inactive,Possible duplicate
18,G019,Elena Rossi,24.0,170.0,NaN,Basic,19.99,2023-02-22,elena.rossi@gmail.com,Active,NaN
19,G020,Elena Rossi,24.0,170.0,55.0,Basic,19.99,2023-02-22,elena.rossi@gmail.com,Active,Duplicate?

In [170]:
df = df[~df['MemberID'].isin(['G008', 'G019'])]
df = df.reset_index(drop=True)
df

,MemberID,Name,Age,Height,Weight,MembershipType,MonthlyFee,JoinDate,Email,Status,Notes
0,G001,Ahsan Reza,29.0,175.0,70.0,Premium,49.99,2023-02-01,ahsan.reza@gmail.com,Active,NaN
1,G002,Meera Nair,34.0,167.6,59.9,Premium,49.99,2023-02-03,meera.nair@gmail.com,Active,NaN
2,G003,Tomasz Kowalski,41.0,180.0,NaN,Basic,19.99,2023-02-05,NaN,Active,No email domain
3,G004,NaN,NaN,168.0,60.0,VIP,99.99,2023-05-02,jenny_oconnor@yahoo.com,Active,Age typo?
4,G005,Carlos Mendes,25.0,NaN,82.0,Basic,19.99,2023-02-08,carlos.mendes@hotmail.com,Inactive,Typo in plan
5,G006,Aiko Sato,31.0,162.0,54.0,Premium,NaN,2023-02-10,aiko.sato@gmail.com,Active,Missing fee
6,G007,Ben Turner,NaN,178.0,75.0,Basic,19.99,2023-10-02,ben.turner@gmail.com,Active,Negative age
7,G009,Ravi Chandran,45.0,171.0,68.0,Premium,49.99,2023-02-12,ravi.chandran@gmail.com,Inactive,Possible duplicate
8,G010,Nadia Popescu,NaN,158.0,50.0,VIP,99.99,2023-12-02,nadia.popescu@gmail.com,Active,Missing age
9,G011,Diego Fernandez,38.0,183.0,90.0,Basic,19.99,2023-02-14,NaN,Active,Bad email format
10,G012,Lin Chen,27.0,165.0,58.0,Premium,49.99,2023-02-15,lin.chen@gmail.com,Active,NaN
11,G013,Grace Osei,52.0,160.0,NaN,VIP,99.99,2023-02-15,grace.osei@gmail.com,Active,NaN
12,G014,Omar Farouk,NaN,177.0,80.0,Basic,19.99,2023-02-17,omar.farouk@gmail.com,Active,VIP trial
13,G015,Sara Kim,33.0,162.6,54.4,Premium,49.99,2023-02-18,sara.kim@gmail.com,Active,NaN
14,G016,Jonas Weber,29.0,182.0,88.0,VIP,0.00,2023-02-19,jonas.weber@gmail.com,Inactive,Fee looks wrong
15,G017,Priya Iyer,36.0,NaN,63.0,Basic,19.99,2023-02-19,priya.iyer@gmail.com,Active,NaN
16,G018,Michael Brown,NaN,174.0,79.0,Premium,49.99,2023-02-21,michael.brown@gmail.com,Active,Age outlier
17,G020,Elena Rossi,24.0,170.0,55.0,Basic,19.99,2023-02-22,elena.rossi@gmail.com,Active,Duplicate?

In [171]:
df.dtypes

MemberID                     str
Name                         str
Age                      float64
Height                   float64
Weight                   float64
MembershipType               str
MonthlyFee               float64
JoinDate          datetime64[us]
Email                        str
Status                       str
Notes                        str
dtype: object

In [172]:
df.isna().sum()

MemberID          0
Name              1
Age               5
Height            2
Weight            2
MembershipType    0
MonthlyFee        1
JoinDate          0
Email             2
Status            0
Notes             6
dtype: int64

In [173]:
df.to_excel('Cleaned.xlsx', index=False)