In [83]:
import pandas as pd
import numpy as np

In [84]:
df = pd.read_csv(r'C:\Users\Junayed\pandas_prac\Aug_2\messy_delivery_day2.csv')

In [85]:
df

,OrderID,CustomerName,Phone,Items,OrderTotal,TipGiven,Rating,DeliveryTime,PaymentMethod,OrderDate,Category,Address
0,D001,Hannah Kim,(212) 555-0143,"Burger, Fries, Coke",$23.50,Yes,5,25 min,Credit Card,2023-03-01,Fast Food,"123 Main St, Springfield, IL 62704"
1,D002,Marco Silva,212-555-0198,"pizza,garlic bread,soda",18,no,4 stars,40,credit_card,03/02/2023,fastfood,"45 Oak Ave Apt 3B, Chicago, IL 60614"
2,D003,Fatima Noor,2125550122,"Salad , Water",$9.99,Y,3/5,1h 5m,CC,2023-03-03,Fine Dining,"77 Pine Rd, Austin TX 73301"
3,D004,Jake Wallace,+1 212 555 0177,"Tacos,Tacos,Chips",$15.00,N,NaN,0h 45m,Cash,05-03-2023,fine dining,"9 Elm St, Denver, CO 80203"
4,D005,Hannah Kim,(212) 555-0143,"Burger, Fries, Coke",$23.50,Yes,5,25 min,Credit Card,2023-03-01,Fast Food,"123 Main St, Springfield, IL 62704"
5,D006,Lucia Fernandez,212.555.0166,"Sushi Roll, Miso Soup",$32.75,1,2,55min,debit card,2023-03-06,Cafe,"200 5th Ave, New York, NY 10010"
6,D007,Derek Brown,NaN,"Burger,Coke",$14.20,0,4,30 min,cash,07/03/2023,Fast Food,"312 Birch Ln, Miami, FL 33101"
7,D008,Sana Malik,(212) 555-0190,"Pad Thai, Spring Rolls, Thai Tea",$27.00,true,5 stars,NaN,Credit Card,2023-03-08,fastfood,"88 Cedar Ct, Seattle, WA 98101"
8,D009,Tom Reilly,212-555-0155,"Wings, Fries",$19.99,false,NaN,20 min,CC,2023-03-09,Fast-Food,"14 Maple Dr, Boston, MA 02108"
9,D010,Grace Liu,2125550111,"Ramen, Gyoza, Green Tea",NaN,Yes,3,1h 10m,credit_card,09-03-2023,Cafe,"501 Union St, Portland, OR 97201"
10,D011,Hannah Kim,(212) 555-0143,"Burger, Fries, Coke",$23.50,Yes,5,25 min,Credit Card,2023-03-01,Fast Food,"123 Main St, Springfield, IL 62704"
11,D012,Omar Siddiqui,212 555 0188,"Curry, Naan, Rice",$21.40,y,4,45 min,Debit Card,2023-03-11,fine dining,"6 Willow Way, Dallas, TX 75201"
12,D013,Ellen Wu,NaN,"Falafel Wrap, Hummus",$11.50,n,2/5,35min,cash,2023-03-12,cafe,"22 Aspen Ct, Phoenix, AZ 85001"
13,D014,Bruno Alves,212-555-0199,"Steak, Mashed Potatoes, Wine",$58.00,Yes,5,1h 20m,Credit Card,12/03/2023,Fine Dining,"310 Highland Ave, Nashville, TN 37201"
14,D015,Priya Desai,(212)5550177,"Dosa, Chutney, Chai",$13.25,Y,4 stars,25min,CC,2023-03-14,fastfood,"77 Palm St, Tampa, FL 33602"
15,D016,Nate Brooks,212-555-0121,"Burger, Onion Rings",$16.80,1,3,30 min,credit_card,2023-03-15,Fast Food,"5 River Rd, Columbus, OH 43004"
16,D017,Alicia Gomez,NaN,"Ceviche, Tostones",$24.60,0,NaN,50 min,Cash,15-03-2023,Fine Dining,"91 Coral Way, San Diego, CA 92101"
17,D018,Ben Turner,212-555-0144,"Pho, Spring Rolls",$18.90,true,5,40min,cc,2023-03-17,fast food,"18 Bay St, San Francisco, CA 94102"
18,D019,Ravi Chandran,212-555-0166,"Biryani, Raita",-$5.00,false,1,1h,Credit Card,2023-03-18,Fine Dining,"63 Lotus Ln, Houston, TX 77002"
19,D020,Nadia Osei,2125550133,"Jollof Rice, Chicken, Plantains",$22.10,Yes,4,45 min,Debit Card,18/03/2023,fastfood,"140 Grove St, Atlanta, GA 30301"
20,D021,Marco Silva,212-555-0198,"pizza,garlic bread,soda",18,no,4 stars,40,credit_card,03/02/2023,fastfood,"45 Oak Ave Apt 3B, Chicago, IL 60614"
21,D022,Yuki Tanaka,212-555-0100,"Ramen, Gyoza",$20.00,y,5,35 min,Cash,2023-03-20,Cafe,"9 Cherry St, Honolulu, HI 96813"
22,D023,Chidi Okafor,212-555-0177,"Jollof Rice, Suya",$19.50,N,3,999 min,CC,2023-03-21,Fast-Food,"27 Ivory Rd, Detroit, MI 48201"
23,D024,Sara Kim,212-555-0155,"Bibimbap, Kimchi",$16.75,Yes,4,30 min,credit_card,2023-03-22,Cafe,"33 Jade Ave, Las Vegas, NV 89101"
24,D025,Leo Fischer,212-555-0166,"Burger, Fries",$13.00,n,2,25 min,cash,2023-03-23,Fast Food,"71 Stone Ct, Orlando, FL 32801"

In [86]:
df.shape

(25, 12)

In [87]:
df.dtypes

OrderID          str
CustomerName     str
Phone            str
Items            str
OrderTotal       str
TipGiven         str
Rating           str
DeliveryTime     str
PaymentMethod    str
OrderDate        str
Category         str
Address          str
dtype: object

In [88]:
df["Phone"] = df["Phone"].astype(str).str.strip()

In [89]:
df.isna().sum()

OrderID          0
CustomerName     0
Phone            3
Items            0
OrderTotal       1
TipGiven         0
Rating           3
DeliveryTime     1
PaymentMethod    0
OrderDate        0
Category         0
Address          0
dtype: int64

In [90]:
import re

def clean_phone_num(val):
    if pd.isna(val):
        return np.nan
    digits = re.sub(r"\D","", str(val))

    if len(digits) == 11 and digits.startswith("1"):
        digits = digits[1:]
    return digits if len(digits) == 10 else np.nan

df["Phone"] = df["Phone"].apply(clean_phone_num)
df["Phone"]

0     2125550143
1     2125550198
2     2125550122
3     2125550177
4     2125550143
5     2125550166
6            NaN
7     2125550190
8     2125550155
9     2125550111
10    2125550143
11    2125550188
12           NaN
13    2125550199
14    2125550177
15    2125550121
16           NaN
17    2125550144
18    2125550166
19    2125550133
20    2125550198
21    2125550100
22    2125550177
23    2125550155
24    2125550166
Name: Phone, dtype: str

In [91]:
df["Phone"] = df["Phone"].apply(lambda x: str(x))
df["Phone"] = df["Phone"].apply(lambda x: x[0:3] + "-" + x[3:6] + "-" + x[6:10])

df["Phone"]

0     212-555-0143
1     212-555-0198
2     212-555-0122
3     212-555-0177
4     212-555-0143
5     212-555-0166
6            nan--
7     212-555-0190
8     212-555-0155
9     212-555-0111
10    212-555-0143
11    212-555-0188
12           nan--
13    212-555-0199
14    212-555-0177
15    212-555-0121
16           nan--
17    212-555-0144
18    212-555-0166
19    212-555-0133
20    212-555-0198
21    212-555-0100
22    212-555-0177
23    212-555-0155
24    212-555-0166
Name: Phone, dtype: str

In [92]:
df["Phone"] = df["Phone"].astype(str).str.replace("nan--", "Unknown")

df["Phone"]

0     212-555-0143
1     212-555-0198
2     212-555-0122
3     212-555-0177
4     212-555-0143
5     212-555-0166
6          Unknown
7     212-555-0190
8     212-555-0155
9     212-555-0111
10    212-555-0143
11    212-555-0188
12         Unknown
13    212-555-0199
14    212-555-0177
15    212-555-0121
16         Unknown
17    212-555-0144
18    212-555-0166
19    212-555-0133
20    212-555-0198
21    212-555-0100
22    212-555-0177
23    212-555-0155
24    212-555-0166
Name: Phone, dtype: str

In [93]:
df["Items"] = df["Items"].apply(
    lambda x: [item.strip().title() for item in str(x).split(",")]
)

df["Items"]

0                  [Burger, Fries, Coke]
1            [Pizza, Garlic Bread, Soda]
2                         [Salad, Water]
3                  [Tacos, Tacos, Chips]
4                  [Burger, Fries, Coke]
5                [Sushi Roll, Miso Soup]
6                         [Burger, Coke]
7     [Pad Thai, Spring Rolls, Thai Tea]
8                         [Wings, Fries]
9              [Ramen, Gyoza, Green Tea]
10                 [Burger, Fries, Coke]
11                   [Curry, Naan, Rice]
12                [Falafel Wrap, Hummus]
13        [Steak, Mashed Potatoes, Wine]
14                 [Dosa, Chutney, Chai]
15                 [Burger, Onion Rings]
16                   [Ceviche, Tostones]
17                   [Pho, Spring Rolls]
18                      [Biryani, Raita]
19     [Jollof Rice, Chicken, Plantains]
20           [Pizza, Garlic Bread, Soda]
21                        [Ramen, Gyoza]
22                   [Jollof Rice, Suya]
23                    [Bibimbap, Kimchi]
24                       [Burger, Fries]
Name: Items, dtype: object

In [94]:
df["OrderTotal"] = pd.to_numeric(df["OrderTotal"].astype(str).str.replace("$","", regex=False).str.strip(), errors='coerce')

df["OrderTotal"]

0     23.50
1     18.00
2      9.99
3     15.00
4     23.50
5     32.75
6     14.20
7     27.00
8     19.99
9       NaN
10    23.50
11    21.40
12    11.50
13    58.00
14    13.25
15    16.80
16    24.60
17    18.90
18    -5.00
19    22.10
20    18.00
21    20.00
22    19.50
23    16.75
24    13.00
Name: OrderTotal, dtype: float64

In [95]:
df.loc[df["OrderTotal"] <0 , "OrderTotal"] = abs(df["OrderTotal"])

df["OrderTotal"]

0     23.50
1     18.00
2      9.99
3     15.00
4     23.50
5     32.75
6     14.20
7     27.00
8     19.99
9       NaN
10    23.50
11    21.40
12    11.50
13    58.00
14    13.25
15    16.80
16    24.60
17    18.90
18     5.00
19    22.10
20    18.00
21    20.00
22    19.50
23    16.75
24    13.00
Name: OrderTotal, dtype: float64

In [96]:
tip_map = {
    "yes": True, "y": True, "1": True, "true": True,
    "no": False, "n": False, "0": False, "false": False
}

df["TipGiven"] = df["TipGiven"].astype(str).str.strip().str.lower().map(tip_map)

In [97]:
def clean_rating(val):
    val = str(val).strip().lower()
    if val in ("nan", "n/a", ""):
        return np.nan
    if "/" in val:
        num, denom = val.split("/")
        return round(float(num) / float(num) *5 ,1)

    try:
        match = "".join(char for char in str(val) if char.isdigit() or char == ".")
        return float(match)
    except ValueError:
        return np.nan

df["Rating"] = df["Rating"].apply(clean_rating)
df["Rating"]

0     5.0
1     4.0
2     5.0
3     NaN
4     5.0
5     2.0
6     4.0
7     5.0
8     NaN
9     3.0
10    5.0
11    4.0
12    5.0
13    5.0
14    4.0
15    3.0
16    NaN
17    5.0
18    1.0
19    4.0
20    4.0
21    5.0
22    3.0
23    4.0
24    2.0
Name: Rating, dtype: float64

In [98]:
def clean_duration(val):
    if pd.isna(val):
        return np.nan

    val = str(val).strip().lower()
    h_match = re.search(r"(\d+)\s*h", val)
    m_match = re.search(r"(\d+)\s*m", val)
    if h_match or m_match:
        hours = int(h_match.group(1) if h_match else 0)
        minutes = int(m_match.group(1) if m_match else 0)
        return hours * 60 + minutes
    num_match = re.search(r"\d+", val)
    return int(num_match.group() if num_match else np.nan)

df["DeliveryTime"] = df["DeliveryTime"].apply(clean_duration)

df.loc[df["DeliveryTime"] > 180 , "DeliveryTime"] = np.nan

df["DeliveryTime"]

0     25.0
1     40.0
2     65.0
3     45.0
4     25.0
5     55.0
6     30.0
7      NaN
8     20.0
9     70.0
10    25.0
11    45.0
12    35.0
13    80.0
14    25.0
15    30.0
16    50.0
17    40.0
18    60.0
19    45.0
20    40.0
21    35.0
22     NaN
23    30.0
24    25.0
Name: DeliveryTime, dtype: float64

In [99]:
pay_map = {
    "credit card": "Credit Card", "cc": "Credit Card",
    "debit card": "Debit Card",
    "cash": "Cash",
}

df["PaymentMethod"] = (df["PaymentMethod"].astype(str).str.strip().str.lower().str.replace("_", " ", regex=False).map(pay_map))

df["PaymentMethod"]

0     Credit Card
1     Credit Card
2     Credit Card
3            Cash
4     Credit Card
5      Debit Card
6            Cash
7     Credit Card
8     Credit Card
9     Credit Card
10    Credit Card
11     Debit Card
12           Cash
13    Credit Card
14    Credit Card
15    Credit Card
16           Cash
17    Credit Card
18    Credit Card
19     Debit Card
20    Credit Card
21           Cash
22    Credit Card
23    Credit Card
24           Cash
Name: PaymentMethod, dtype: str

In [100]:
df["OrderDate"] = pd.to_datetime(df["OrderDate"], format= 'mixed', dayfirst=True).dt.strftime("%Y-%m-%d")

df["OrderDate"]

0     2023-01-03
1     2023-02-03
2     2023-03-03
3     2023-03-05
4     2023-01-03
5     2023-06-03
6     2023-03-07
7     2023-08-03
8     2023-09-03
9     2023-03-09
10    2023-01-03
11    2023-11-03
12    2023-12-03
13    2023-03-12
14    2023-03-14
15    2023-03-15
16    2023-03-15
17    2023-03-17
18    2023-03-18
19    2023-03-18
20    2023-02-03
21    2023-03-20
22    2023-03-21
23    2023-03-22
24    2023-03-23
Name: OrderDate, dtype: str

In [101]:
df["Category"].value_counts()

Category
Fast Food      6
fastfood       5
Fine Dining    4
Cafe           4
fine dining    2
Fast-Food      2
cafe           1
fast food      1
Name: count, dtype: int64

In [102]:
category_map = {
    "fast food": "Fast Food",
    "fastfood": "Fast Food",
    "fast-food": "Fast Food",
    "fine dining": "Fine Dining",
    "cafe": "Cafe"
}

df["Category"] = df["Category"].astype(str).str.strip().str.lower()
df["Category"] = df["Category"].map(category_map)
df["Category"]

0       Fast Food
1       Fast Food
2     Fine Dining
3     Fine Dining
4       Fast Food
5            Cafe
6       Fast Food
7       Fast Food
8       Fast Food
9            Cafe
10      Fast Food
11    Fine Dining
12           Cafe
13    Fine Dining
14      Fast Food
15      Fast Food
16    Fine Dining
17      Fast Food
18    Fine Dining
19      Fast Food
20      Fast Food
21           Cafe
22      Fast Food
23           Cafe
24      Fast Food
Name: Category, dtype: str

In [103]:
df["Zip"] = df["Address"].str.extract(r"(\d{5})$")
df[["Address", "Zip"]]

                                  Address    Zip
0      123 Main St, Springfield, IL 62704  62704
1    45 Oak Ave Apt 3B, Chicago, IL 60614  60614
2             77 Pine Rd, Austin TX 73301  73301
3              9 Elm St, Denver, CO 80203  80203
4      123 Main St, Springfield, IL 62704  62704
5         200 5th Ave, New York, NY 10010  10010
6           312 Birch Ln, Miami, FL 33101  33101
7          88 Cedar Ct, Seattle, WA 98101  98101
8           14 Maple Dr, Boston, MA 02108  02108
9        501 Union St, Portland, OR 97201  97201
10     123 Main St, Springfield, IL 62704  62704
11         6 Willow Way, Dallas, TX 75201  75201
12         22 Aspen Ct, Phoenix, AZ 85001  85001
13  310 Highland Ave, Nashville, TN 37201  37201
14            77 Palm St, Tampa, FL 33602  33602
15         5 River Rd, Columbus, OH 43004  43004
16      91 Coral Way, San Diego, CA 92101  92101
17     18 Bay St, San Francisco, CA 94102  94102
18         63 Lotus Ln, Houston, TX 77002  77002
19        140 Grove St, Atlanta, GA 30301  30301
20   45 Oak Ave Apt 3B, Chicago, IL 60614  60614
21        9 Cherry St, Honolulu, HI 96813  96813
22         27 Ivory Rd, Detroit, MI 48201  48201
23       33 Jade Ave, Las Vegas, NV 89101  89101
24         71 Stone Ct, Orlando, FL 32801  32801

In [104]:
target_col = df.columns.get_loc("Address")
zip_code = df["Zip"]

df.insert(target_col + 1, "Zip", df.pop("Zip"))
df

,OrderID,CustomerName,Phone,Items,OrderTotal,TipGiven,Rating,DeliveryTime,PaymentMethod,OrderDate,Category,Address,Zip
0,D001,Hannah Kim,212-555-0143,"[Burger, Fries, Coke]",23.50,True,5.0,25.0,Credit Card,2023-01-03,Fast Food,"123 Main St, Springfield, IL 62704",62704
1,D002,Marco Silva,212-555-0198,"[Pizza, Garlic Bread, Soda]",18.00,False,4.0,40.0,Credit Card,2023-02-03,Fast Food,"45 Oak Ave Apt 3B, Chicago, IL 60614",60614
2,D003,Fatima Noor,212-555-0122,"[Salad, Water]",9.99,True,5.0,65.0,Credit Card,2023-03-03,Fine Dining,"77 Pine Rd, Austin TX 73301",73301
3,D004,Jake Wallace,212-555-0177,"[Tacos, Tacos, Chips]",15.00,False,NaN,45.0,Cash,2023-03-05,Fine Dining,"9 Elm St, Denver, CO 80203",80203
4,D005,Hannah Kim,212-555-0143,"[Burger, Fries, Coke]",23.50,True,5.0,25.0,Credit Card,2023-01-03,Fast Food,"123 Main St, Springfield, IL 62704",62704
5,D006,Lucia Fernandez,212-555-0166,"[Sushi Roll, Miso Soup]",32.75,True,2.0,55.0,Debit Card,2023-06-03,Cafe,"200 5th Ave, New York, NY 10010",10010
6,D007,Derek Brown,Unknown,"[Burger, Coke]",14.20,False,4.0,30.0,Cash,2023-03-07,Fast Food,"312 Birch Ln, Miami, FL 33101",33101
7,D008,Sana Malik,212-555-0190,"[Pad Thai, Spring Rolls, Thai Tea]",27.00,True,5.0,NaN,Credit Card,2023-08-03,Fast Food,"88 Cedar Ct, Seattle, WA 98101",98101
8,D009,Tom Reilly,212-555-0155,"[Wings, Fries]",19.99,False,NaN,20.0,Credit Card,2023-09-03,Fast Food,"14 Maple Dr, Boston, MA 02108",02108
9,D010,Grace Liu,212-555-0111,"[Ramen, Gyoza, Green Tea]",NaN,True,3.0,70.0,Credit Card,2023-03-09,Cafe,"501 Union St, Portland, OR 97201",97201
10,D011,Hannah Kim,212-555-0143,"[Burger, Fries, Coke]",23.50,True,5.0,25.0,Credit Card,2023-01-03,Fast Food,"123 Main St, Springfield, IL 62704",62704
11,D012,Omar Siddiqui,212-555-0188,"[Curry, Naan, Rice]",21.40,True,4.0,45.0,Debit Card,2023-11-03,Fine Dining,"6 Willow Way, Dallas, TX 75201",75201
12,D013,Ellen Wu,Unknown,"[Falafel Wrap, Hummus]",11.50,False,5.0,35.0,Cash,2023-12-03,Cafe,"22 Aspen Ct, Phoenix, AZ 85001",85001
13,D014,Bruno Alves,212-555-0199,"[Steak, Mashed Potatoes, Wine]",58.00,True,5.0,80.0,Credit Card,2023-03-12,Fine Dining,"310 Highland Ave, Nashville, TN 37201",37201
14,D015,Priya Desai,212-555-0177,"[Dosa, Chutney, Chai]",13.25,True,4.0,25.0,Credit Card,2023-03-14,Fast Food,"77 Palm St, Tampa, FL 33602",33602
15,D016,Nate Brooks,212-555-0121,"[Burger, Onion Rings]",16.80,True,3.0,30.0,Credit Card,2023-03-15,Fast Food,"5 River Rd, Columbus, OH 43004",43004
16,D017,Alicia Gomez,Unknown,"[Ceviche, Tostones]",24.60,False,NaN,50.0,Cash,2023-03-15,Fine Dining,"91 Coral Way, San Diego, CA 92101",92101
17,D018,Ben Turner,212-555-0144,"[Pho, Spring Rolls]",18.90,True,5.0,40.0,Credit Card,2023-03-17,Fast Food,"18 Bay St, San Francisco, CA 94102",94102
18,D019,Ravi Chandran,212-555-0166,"[Biryani, Raita]",5.00,False,1.0,60.0,Credit Card,2023-03-18,Fine Dining,"63 Lotus Ln, Houston, TX 77002",77002
19,D020,Nadia Osei,212-555-0133,"[Jollof Rice, Chicken, Plantains]",22.10,True,4.0,45.0,Debit Card,2023-03-18,Fast Food,"140 Grove St, Atlanta, GA 30301",30301
20,D021,Marco Silva,212-555-0198,"[Pizza, Garlic Bread, Soda]",18.00,False,4.0,40.0,Credit Card,2023-02-03,Fast Food,"45 Oak Ave Apt 3B, Chicago, IL 60614",60614
21,D022,Yuki Tanaka,212-555-0100,"[Ramen, Gyoza]",20.00,True,5.0,35.0,Cash,2023-03-20,Cafe,"9 Cherry St, Honolulu, HI 96813",96813
22,D023,Chidi Okafor,212-555-0177,"[Jollof Rice, Suya]",19.50,False,3.0,NaN,Credit Card,2023-03-21,Fast Food,"27 Ivory Rd, Detroit, MI 48201",48201
23,D024,Sara Kim,212-555-0155,"[Bibimbap, Kimchi]",16.75,True,4.0,30.0,Credit Card,2023-03-22,Cafe,"33 Jade Ave, Las Vegas, NV 89101",89101
24,D025,Leo Fischer,212-555-0166,"[Burger, Fries]",13.00,False,2.0,25.0,Cash,2023-03-23,Fast Food,"71 Stone Ct, Orlando, FL 32801",32801

In [105]:

df["Items_key"] = df["Items"].apply(lambda x: tuple(x))

df[df.duplicated(subset=["CustomerName","Phone","Items_key","OrderDate"], keep = False)]

,OrderID,CustomerName,Phone,Items,OrderTotal,TipGiven,Rating,DeliveryTime,PaymentMethod,OrderDate,Category,Address,Zip,Items_key
0,D001,Hannah Kim,212-555-0143,"[Burger, Fries, Coke]",23.5,True,5.0,25.0,Credit Card,2023-01-03,Fast Food,"123 Main St, Springfield, IL 62704",62704,"(Burger, Fries, Coke)"
1,D002,Marco Silva,212-555-0198,"[Pizza, Garlic Bread, Soda]",18.0,False,4.0,40.0,Credit Card,2023-02-03,Fast Food,"45 Oak Ave Apt 3B, Chicago, IL 60614",60614,"(Pizza, Garlic Bread, Soda)"
4,D005,Hannah Kim,212-555-0143,"[Burger, Fries, Coke]",23.5,True,5.0,25.0,Credit Card,2023-01-03,Fast Food,"123 Main St, Springfield, IL 62704",62704,"(Burger, Fries, Coke)"
10,D011,Hannah Kim,212-555-0143,"[Burger, Fries, Coke]",23.5,True,5.0,25.0,Credit Card,2023-01-03,Fast Food,"123 Main St, Springfield, IL 62704",62704,"(Burger, Fries, Coke)"
20,D021,Marco Silva,212-555-0198,"[Pizza, Garlic Bread, Soda]",18.0,False,4.0,40.0,Credit Card,2023-02-03,Fast Food,"45 Oak Ave Apt 3B, Chicago, IL 60614",60614,"(Pizza, Garlic Bread, Soda)"

In [106]:
df = df.drop_duplicates(subset=["CustomerName","Phone","Items_key","OrderDate"], keep="first")
df = df.drop(columns= "Items_key").reset_index(drop=True)
df

,OrderID,CustomerName,Phone,Items,OrderTotal,TipGiven,Rating,DeliveryTime,PaymentMethod,OrderDate,Category,Address,Zip
0,D001,Hannah Kim,212-555-0143,"[Burger, Fries, Coke]",23.50,True,5.0,25.0,Credit Card,2023-01-03,Fast Food,"123 Main St, Springfield, IL 62704",62704
1,D002,Marco Silva,212-555-0198,"[Pizza, Garlic Bread, Soda]",18.00,False,4.0,40.0,Credit Card,2023-02-03,Fast Food,"45 Oak Ave Apt 3B, Chicago, IL 60614",60614
2,D003,Fatima Noor,212-555-0122,"[Salad, Water]",9.99,True,5.0,65.0,Credit Card,2023-03-03,Fine Dining,"77 Pine Rd, Austin TX 73301",73301
3,D004,Jake Wallace,212-555-0177,"[Tacos, Tacos, Chips]",15.00,False,NaN,45.0,Cash,2023-03-05,Fine Dining,"9 Elm St, Denver, CO 80203",80203
4,D006,Lucia Fernandez,212-555-0166,"[Sushi Roll, Miso Soup]",32.75,True,2.0,55.0,Debit Card,2023-06-03,Cafe,"200 5th Ave, New York, NY 10010",10010
5,D007,Derek Brown,Unknown,"[Burger, Coke]",14.20,False,4.0,30.0,Cash,2023-03-07,Fast Food,"312 Birch Ln, Miami, FL 33101",33101
6,D008,Sana Malik,212-555-0190,"[Pad Thai, Spring Rolls, Thai Tea]",27.00,True,5.0,NaN,Credit Card,2023-08-03,Fast Food,"88 Cedar Ct, Seattle, WA 98101",98101
7,D009,Tom Reilly,212-555-0155,"[Wings, Fries]",19.99,False,NaN,20.0,Credit Card,2023-09-03,Fast Food,"14 Maple Dr, Boston, MA 02108",02108
8,D010,Grace Liu,212-555-0111,"[Ramen, Gyoza, Green Tea]",NaN,True,3.0,70.0,Credit Card,2023-03-09,Cafe,"501 Union St, Portland, OR 97201",97201
9,D012,Omar Siddiqui,212-555-0188,"[Curry, Naan, Rice]",21.40,True,4.0,45.0,Debit Card,2023-11-03,Fine Dining,"6 Willow Way, Dallas, TX 75201",75201
10,D013,Ellen Wu,Unknown,"[Falafel Wrap, Hummus]",11.50,False,5.0,35.0,Cash,2023-12-03,Cafe,"22 Aspen Ct, Phoenix, AZ 85001",85001
11,D014,Bruno Alves,212-555-0199,"[Steak, Mashed Potatoes, Wine]",58.00,True,5.0,80.0,Credit Card,2023-03-12,Fine Dining,"310 Highland Ave, Nashville, TN 37201",37201
12,D015,Priya Desai,212-555-0177,"[Dosa, Chutney, Chai]",13.25,True,4.0,25.0,Credit Card,2023-03-14,Fast Food,"77 Palm St, Tampa, FL 33602",33602
13,D016,Nate Brooks,212-555-0121,"[Burger, Onion Rings]",16.80,True,3.0,30.0,Credit Card,2023-03-15,Fast Food,"5 River Rd, Columbus, OH 43004",43004
14,D017,Alicia Gomez,Unknown,"[Ceviche, Tostones]",24.60,False,NaN,50.0,Cash,2023-03-15,Fine Dining,"91 Coral Way, San Diego, CA 92101",92101
15,D018,Ben Turner,212-555-0144,"[Pho, Spring Rolls]",18.90,True,5.0,40.0,Credit Card,2023-03-17,Fast Food,"18 Bay St, San Francisco, CA 94102",94102
16,D019,Ravi Chandran,212-555-0166,"[Biryani, Raita]",5.00,False,1.0,60.0,Credit Card,2023-03-18,Fine Dining,"63 Lotus Ln, Houston, TX 77002",77002
17,D020,Nadia Osei,212-555-0133,"[Jollof Rice, Chicken, Plantains]",22.10,True,4.0,45.0,Debit Card,2023-03-18,Fast Food,"140 Grove St, Atlanta, GA 30301",30301
18,D022,Yuki Tanaka,212-555-0100,"[Ramen, Gyoza]",20.00,True,5.0,35.0,Cash,2023-03-20,Cafe,"9 Cherry St, Honolulu, HI 96813",96813
19,D023,Chidi Okafor,212-555-0177,"[Jollof Rice, Suya]",19.50,False,3.0,NaN,Credit Card,2023-03-21,Fast Food,"27 Ivory Rd, Detroit, MI 48201",48201
20,D024,Sara Kim,212-555-0155,"[Bibimbap, Kimchi]",16.75,True,4.0,30.0,Credit Card,2023-03-22,Cafe,"33 Jade Ave, Las Vegas, NV 89101",89101
21,D025,Leo Fischer,212-555-0166,"[Burger, Fries]",13.00,False,2.0,25.0,Cash,2023-03-23,Fast Food,"71 Stone Ct, Orlando, FL 32801",32801

In [107]:
df.dtypes

OrderID              str
CustomerName         str
Phone                str
Items             object
OrderTotal       float64
TipGiven            bool
Rating           float64
DeliveryTime     float64
PaymentMethod        str
OrderDate            str
Category             str
Address              str
Zip                  str
dtype: object

In [108]:
df.isna().sum()

OrderID          0
CustomerName     0
Phone            0
Items            0
OrderTotal       1
TipGiven         0
Rating           3
DeliveryTime     2
PaymentMethod    0
OrderDate        0
Category         0
Address          0
Zip              0
dtype: int64

In [109]:
df["Items"] = df["Items"].apply(lambda x: ", ".join(x))
df.to_excel("Cleaned_delivery.xlsx", index=False)