In [31]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

In [32]:
df = pd.read_csv(r"C:\Users\Junayed\pandas_prac\Aug_26\messy_vetclinic.csv")

In [33]:
df.head(5)

,PatientID,PetName,Species,Breed,OwnerName,OwnerPhone,VisitDate,AgeYears,WeightKg,Vaccinated,VisitReason,Cost,Notes
0,V001,Buddy,Dog,Labrador,Sarah Kim,(415) 555-0142,2024-03-11,4.0,28.5,Yes,Checkup,65.00,NaN
1,V002,MAX,dog,Poodle,james ortiz,415-555-0198,03/12/2024,7.0,12.3,yes,Vaccination,45.00,NaN
2,V003,Bella,Cat,Siamese,Maria Chen,(628) 555-0110,2024-03-12,2.0,4.1,No,Grooming,40.00,NaN
3,V004,Charlie,CAT,Domestic Shorthair,Tom Reyes,6285550177,12-Mar-2024,1.0,3.8 kg,N,Vaccination,45.00,NaN
4,V005,Daisy,Rabbit,Holland Lop,Priya Nair,(510) 555-0199,2024-03-13,-1.0,1.9,Yes,Checkup,55.00,Owner unsure of age

In [34]:
df["PetName"] = df["PetName"].str.strip().str.title()

In [35]:
df["Species"].value_counts()

Species
Dog       17
Cat        9
Rabbit     5
cat        4
Bird       3
dog        1
CAT        1
RABBIT     1
cat        1
Name: count, dtype: int64

In [36]:
df["Species"] = df["Species"].str.strip().str.title()

In [37]:
df["Species"].value_counts()

Species
Dog       18
Cat       15
Rabbit     6
Bird       3
Name: count, dtype: int64

In [38]:
df["Breed"] = df["Breed"].str.strip().str.title()

In [39]:
df["OwnerName"] = df["OwnerName"].str.strip().str.title()

In [40]:
df["OwnerPhone"] = df["OwnerPhone"].str.replace(r"[()-. ]", "", regex=True)
def clean_number(val):
    if pd.isna(val):
        return np.nan
    elif len(val) == 10:
        return f"{val[0:3]}-{val[3:6]}-{val[6:10]}"
    else:
        return val

df["OwnerPhone"] = df["OwnerPhone"].apply(clean_number)
df[["PatientID", "OwnerPhone"]]

   PatientID    OwnerPhone
0       V001  415-555-0142
1       V002  415-555-0198
2       V003  628-555-0110
3       V004  628-555-0177
4       V005  510-555-0199
5       V006  510-555-0134
6       V007  415-555-0177
7       V008  415-555-01O0
8       V009  628-555-0155
9       V010           NaN
10      V011  415-555-0163
11      V012  510-555-0112
12      V013  510-555-0126
13      V014  628-555-0122
14      V015  628-555-0170
15      V016  415-555-0130
16      V017  510-555-0161
17      V018  628-555-0131
18      V019  628-555-0188
19      V020  415-555-0177
20      V021  415-555-0190
21      V022  510-555-0173
22      V023  628-555-0193
23      V024  415-555-0103
24      V025  510-555-0147
25      V026  628-555-0185
26      V027  415-555-01O0
27      V028  510-555-0152
28      V029  628-555-0105
29      V030  415-555-0134
30      V031  510-555-0125
31      V032  628-555-0144
32      V033  415-555-0149
33      V034  510-555-0162
34      V035  628-555-0141
35      V036  415-555-0159
36      V037  510-555-0171
37      V038  628-555-0118
38      V039  415-555-0105
39      V040  510-555-0199
40      V041  628-555-0177
41      V042  415-555-0129

In [43]:
df.loc[df["OwnerPhone"].isna(), "Notes"] = "Update Phone no."

In [45]:
df["VisitDate"] = pd.to_datetime(df["VisitDate"], format='mixed', errors='coerce')
df["VisitDate"]

0    2024-03-11
1    2024-03-12
2    2024-03-12
3    2024-03-12
4    2024-03-13
5    2024-03-13
6    2024-03-14
7    2024-03-14
8    2024-03-15
9    2024-03-15
10   2024-03-15
11   2024-03-15
12   2024-03-16
13   2024-03-16
14   2024-03-16
15   2024-03-17
16   2024-03-17
17   2024-03-18
18   2024-03-18
19   2024-03-19
20   2024-03-19
21   2024-03-19
22   2024-03-20
23   2024-03-20
24   2024-03-21
25   2024-03-21
26   2024-03-21
27   2024-03-22
28   2024-03-22
29   2024-03-23
30   2024-03-23
31   2024-03-24
32   2024-03-24
33   2024-03-25
34   2024-03-25
35   2024-03-26
36   2024-03-26
37   2024-03-27
38   2024-03-27
39   2024-03-28
40   2024-03-28
41   2024-03-29
Name: VisitDate, dtype: datetime64[us]

In [47]:
df.loc[df["AgeYears"] < 0, ["PatientID", "PetName", "Species", "AgeYears", "Notes"]]

   PatientID PetName Species  AgeYears                Notes
4       V005   Daisy  Rabbit      -1.0  Owner unsure of age
19      V020   Gizmo    Bird      -1.0                  NaN

In [48]:
df.loc[df["AgeYears"] > 30, ["PatientID", "PetName", "Species", "AgeYears", "Notes"]]

   PatientID PetName Species  AgeYears                             Notes
15      V016    Ruby     Dog      99.0  Age looks off, verify with owner

In [50]:
df.loc[(df["AgeYears"] < 0) | (df["AgeYears"] > 30), "AgeYears"] = np.nan

In [51]:
df

,PatientID,PetName,Species,Breed,OwnerName,OwnerPhone,VisitDate,AgeYears,WeightKg,Vaccinated,VisitReason,Cost,Notes
0,V001,Buddy,Dog,Labrador,Sarah Kim,415-555-0142,2024-03-11,4.0,28.5,Yes,Checkup,65.00,NaN
1,V002,Max,Dog,Poodle,James Ortiz,415-555-0198,2024-03-12,7.0,12.3,yes,Vaccination,45.00,NaN
2,V003,Bella,Cat,Siamese,Maria Chen,628-555-0110,2024-03-12,2.0,4.1,No,Grooming,40.00,NaN
3,V004,Charlie,Cat,Domestic Shorthair,Tom Reyes,628-555-0177,2024-03-12,1.0,3.8 kg,N,Vaccination,45.00,NaN
4,V005,Daisy,Rabbit,Holland Lop,Priya Nair,510-555-0199,2024-03-13,NaN,1.9,Yes,Checkup,55.00,Owner unsure of age
5,V006,Rocky,Dog,Bulldog,Owen Marsh,510-555-0134,2024-03-13,6.0,999,No,Surgery,"1,200.00",Weight likely a data entry error
6,V007,Luna,Cat,Maine Coon,Elena Voss,415-555-0177,2024-03-14,3.0,5.6,Yes,Checkup,60.00,NaN
7,V008,Milo,Dog,Beagle,Hank Renner,415-555-01O0,2024-03-14,5.0,10.1,1,Grooming,38.00,NaN
8,V009,Coco,Bird,Parakeet,Dana Marsh,628-555-0155,2024-03-15,1.0,0.03,No,Checkup,30.00,NaN
9,V010,Simba,Cat,Bengal,Rico Callahan,NaN,2024-03-15,4.0,4.9,Yes,Vaccination,45.00,Update Phone no.
10,V011,Simba,Cat,Bengal,Rico Callahan,415-555-0163,2024-03-15,4.0,4.9,Yes,Vaccination,45.00,NaN
11,V012,Zoe,Dog,Golden Retriever,Faye Kowalski,510-555-0112,2024-03-15,8.0,31.2,Yes,Surgery,1150.00,NaN
12,V013,Oscar,Rabbit,Netherland Dwarf,Bruno Farrell,510-555-0126,2024-03-16,2.0,1.5,No,Checkup,15.00,NaN
13,V014,Chloe,Dog,Poodle,Alina Amaro,628-555-0122,2024-03-16,3.0,9.4,Yes,Grooming,42.00,NaN
14,V015,Leo,Cat,Persian,Chet Vance,628-555-0170,2024-03-16,5.0,4.5,N,Checkup,60.00,NaN
15,V016,Ruby,Dog,Terrier Mix,Ines Petrov,415-555-0130,2024-03-17,NaN,22.0,Yes,Checkup,65.00,"Age looks off, verify with owner"
16,V017,Bear,Dog,Mastiff,Roy Duarte,510-555-0161,2024-03-17,6.0,999,Yes,Checkup,65.00,Scale malfunction noted by tech
17,V018,Nala,Cat,Ragdoll,Wendy Falk,628-555-0131,2024-03-18,2.0,4.2 kg,No,Vaccination,45.00,NaN
18,V019,Duke,Dog,German Shepherd,Damon Beck,628-555-0188,2024-03-18,7.0,34.6,Yes,Surgery,1450.00,NaN
19,V020,Gizmo,Bird,Cockatiel,Kira Sato,415-555-0177,2024-03-19,NaN,0.09,No,Checkup,30.00,NaN
20,V021,Peanut,Rabbit,Lionhead,Nate Kessler,415-555-0190,2024-03-19,1.0,1.7,yes,Vaccination,40.00,NaN
21,V022,Shadow,Cat,Tabby,Sonia Hollis,510-555-0173,2024-03-19,4.0,4.0,No,chekup,60.00,NaN
22,V023,Toby,Dog,Corgi,Gus Larsen,628-555-0193,2024-03-20,3.0,11.8,Yes,Grooming,38.00,NaN
23,V024,Lily,Cat,Domestic Longhair,Talia Fontaine,415-555-0103,2024-03-20,6.0,5.1,Yes,Checkup,60.00,NaN
24,V025,Jack,Dog,Boxer,Rex Adams,510-555-0147,2024-03-21,5.0,27.9,0,VACCINATION,45.00,NaN
25,V026,Sadie,Rabbit,Rex,Ivy Cruz,628-555-0185,2024-03-21,2.0,2.1,No,Checkup,50.00,NaN
26,V027,Cooper,Dog,Husky,Leon Rossi,415-555-01O0,2024-03-21,4.0,23.4,Yes,Surgery,1300.00,NaN
27,V028,Willow,Cat,Tabby,Mara Weber,510-555-0152,2024-03-22,3.0,4.4,Y,Grooming,40.00,NaN
28,V029,Rex,Dog,Rottweiler,Otto Chen,628-555-0105,2024-03-22,7.0,40.2,Yes,Checkup,65.00,NaN
29,V030,Molly,Cat,Sphynx,Reyna Novak,415-555-0134,2024-03-23,1.0,3.6,No,Vaccination,45.00,Duplicate entry?
30,V031,Ginger,Dog,Dachshund,Cole Silva,510-555-0125,2024-03-23,5.0,8.9,Yes,Grooming,38.00,NaN
31,V032,Loki,Cat,Bombay,Beth Muller,628-555-0144,2024-03-24,2.0,4.3,Yes,Checkup,60.00,NaN
32,V033,Frankie,Rabbit,Flemish Giant,Drew Khan,415-555-0149,2024-03-24,3.0,6.8,No,Checkup,55.00,NaN
33,V034,Pepper,Dog,Chihuahua,Alma Diaz,510-555-0162,2024-03-25,8.0,2.6,Yes,Surgery,1050.00,NaN
34,V035,Biscuit,Cat,Calico,Ezra Bauer,628-555-0141,2024-03-25,4.0,4.7,Yes,Vaccination,45.00,NaN
35,V036,Rusty,Dog,Beagle,Cass Singh,415-555-0159,2024-03-26,NaN,NaN,No,Checkup,65.00,"Owner cancelled visit, only fee logged"
36,V037,Misty,Bird,Cockatoo,Trina Haddad,510-555-0171,2024-03-26,3.0,0.45,Yes,Checkup,35.00,NaN
37,V038,Buster,Dog,Great Dane,Hugo Nakamura,628-555-0118,2024-03-27,2.0,52.0,Yes,Surgery,1500.00,NaN
38,V039,Olive,Cat,British Shorthair,Nadia Wren,415-555-0105,2024-03-27,5.0,4.8,No,Grooming,40.00,NaN
39,V040,Finn,Dog,Border Collie,Marcus Reyes,510-555-0199,2024-03-28,3.0,18.3,Yes,Checkup,65.00,NaN
40,V041,Rosie,Rabbit,Angora,Elena Voss,628-555-0177,2024-03-28,2.0,2.3,yes,Vaccination,40.00,NaN
41,V042,Peanut,Cat,Persian,Owen Marsh,415-555-0129,2024-03-29,1.0,3.9,No,checkup,60.00,NaN