In [14]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

In [15]:
df = pd.read_csv(r"C:\Users\Junayed\pandas_prac\Aug_29\messy_autoshop.csv")

In [16]:
df.head(5)

,WorkOrderID,CustomerName,CustomerPhone,VehicleMake,VehicleModel,VehicleYear,ServiceDate,ServiceType,LaborHours,PartsCost,LaborCost,TotalCost,WarrantyCovered,Notes
0,WO001,Marcus Bellweather,(415) 555-0121,Toyota,Camry,2005,2024-04-01,Oil Change,0.5h,36.17,37.5,73.67,1,NaN
1,WO002,kelly nguyen,415-555-0166,Honda,Civic,2006,04/02/2024,TIRE ROTATION,0.5 hrs,7.88,37.5,45.38,FALSE,NaN
2,WO003,Priya Shah,(510) 555-0134,Ford,F-150,2007,02-Apr-2024,battery replacement,60 min,112.73,75.0,187.73,TRUE,NaN
3,WO004,Dominic Russo,510.555.0148,Chevrolet,Malibu,2008,2024-04-03,Brake Repair,2.0,118.06,150.0,268.06,0,NaN
4,WO005,Tanya Whitfield,(628) 555-0177,Nissan,Altima,2009,04/04/2024,engine diagnostic,3.0h,50.30,225.0,275.3,No,NaN

In [17]:
df.shape

(46, 14)

In [18]:
df.dtypes

WorkOrderID            str
CustomerName           str
CustomerPhone          str
VehicleMake            str
VehicleModel           str
VehicleYear          int64
ServiceDate            str
ServiceType            str
LaborHours             str
PartsCost          float64
LaborCost          float64
TotalCost              str
WarrantyCovered        str
Notes                  str
dtype: object

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   WorkOrderID      46 non-null     str
 1   CustomerName     46 non-null     str
 2   CustomerPhone    44 non-null     str
 3   VehicleMake      46 non-null     str
 4   VehicleModel     46 non-null     str
 5   VehicleYear      46 non-null     int64
 6   ServiceDate      46 non-null     str
 7   ServiceType      46 non-null     str
 8   LaborHours       46 non-null     str
 9   PartsCost        46 non-null     float64
 10  LaborCost        46 non-null     float64
 11  TotalCost        46 non-null     str
 12  WarrantyCovered  46 non-null     str
 13  Notes            2 non-null      str
dtypes: float64(2), int64(1), str(11)
memory usage: 8.9 KB

### Clean and Standardize Customer Names

* **Remove Extra Whitespace:** Strips leading and trailing spaces from text entries using `.str.strip()`.
* **Standardize Casing:** Converts all names to title case using `.str.title()` for uniform formatting.
* **Verification:** Displays the cleaned `CustomerName` column to verify changes.

In [20]:
df["CustomerName"] = df["CustomerName"].str.strip().str.title()
df["CustomerName"]

0      Marcus Bellweather
1            Kelly Nguyen
2              Priya Shah
3           Dominic Russo
4         Tanya Whitfield
5           Earl Jacobson
6              Nadia Osei
7        Miles Chatterjee
8          Renata Alvarez
9            Simon Truong
10          Beatrice Lund
11       Hector Maldonado
12         Fiona Whitaker
13           Grady Osment
14         Camille Rourke
15      Vincent Kowalczyk
16           Layla Farrow
17             Omar Reyes
18        Petra Lindqvist
19         Desmond Clarke
20          Ingrid Solano
21       Julius Marchetti
22         Nora Delacroix
23           Wade Ashford
24       Selena Prokopiev
25         Tobias Nkemelu
26          Harriet Bosco
27      Elias Vantongeren
28         Corinne Fasano
29    Byron Hollingsworth
30          Adaeze Chukwu
31          Milo Everhart
32        Sabrina Okonkwo
33        Rutger Van Dyke
34         Yasmin Delgado
35          Cormac Blythe
36      Whitney Sarnowski
37             Priya Shah
38             Priya Shah
39          Marisol Trejo
40       Quentin Aldridge
41     Bridget Mcallister
42           Salim Farouk
43      Odette Villanueva
44         Trent Kowalski
45        Genevieve Ashby
Name: CustomerName, dtype: str

### Clean and Format `CustomerPhone`

**Issues Identified:**
* Inconsistent phone number formatting across records (e.g., `(XXX) XXX-XXXX`, `XXX.XXX.XXXX`, `XXXXXXXXXX`, and `XXX-XXX-XXXX`).
* Presence of non-numeric punctuation, special characters, and missing values (`NaN`).

**Cleaning Steps:**
* **Missing Value Handling:** Returns `np.nan` immediately if the phone number entry is null (`pd.isna()`).
* **Digit Extraction:** Strips all non-numeric characters using `re.sub(r"\D", "", str(val))` to isolate raw digits.
* **Length Validation & Standardization:** Validates that the number contains exactly 10 digits and reformats it to `XXX-XXX-XXXX`. Any record that fails the length check is set to `np.nan`.
* **Application:** Applies the transformation to the `CustomerPhone` column and displays the series to verify changes.

In [21]:
def Clean_PhoneNumber(val):
    if pd.isna(val):
        return np.nan
    digits = re.sub(r"\D", "", str(val))
    if len(digits) == 10:
        return f"{digits[0:3]}-{digits[3:6]}-{digits[6:10]}"
    return np.nan

df["CustomerPhone"] = df["CustomerPhone"].apply(Clean_PhoneNumber)
df["CustomerPhone"]

0     415-555-0121
1     415-555-0166
2     510-555-0134
3     510-555-0148
4     628-555-0177
5     628-555-0190
6              NaN
7     415-555-0155
8     510-555-0113
9     510-555-0129
10    628-555-0161
11    628-555-0173
12    415-555-0188
13    415-555-0104
14    510-555-0197
15    510-555-0116
16    628-555-0139
17    628-555-0152
18    415-555-0163
19    415-555-0178
20    510-555-0122
21    510-555-0135
22    628-555-0146
23    628-555-0159
24    415-555-0184
25    415-555-0195
26    510-555-0107
27    510-555-0118
28    628-555-0129
29    628-555-0143
30    415-555-0156
31    415-555-0169
32    510-555-0181
33    510-555-0192
34    628-555-0103
35    628-555-0114
36    415-555-0127
37             NaN
38    510-555-0134
39    510-555-0141
40    628-555-0165
41    628-555-0176
42    415-555-0187
43    415-555-0119
44    510-555-0131
45    510-555-0142
Name: CustomerPhone, dtype: str

In [22]:
df["VehicleMake"].value_counts()

VehicleMake
Ford          6
Toyota        5
Honda         5
Chevrolet     5
Nissan        5
Subaru        4
Mazda         4
Hyundai       4
Kia           2
Volkswagen    2
BMW           2
Jeep          2
Name: count, dtype: int64

### Inspect and Convert `VehicleMake` Data Type

**Issues Identified:**
* Need to verify distribution, check for rare or unexpected values, and ensure uniform string data types across all vehicle make entries.

**Cleaning Steps:**
* **Distribution Check:** Uses `.value_counts()` to inspect the frequency distribution of vehicle makes and detect any anomalies or typos.
* **Type Casting:** Converts the `VehicleMake` column explicitly to string format (`.astype(str)`) to prevent mixed data types and ensure compatibility for downstream text processing.

In [23]:
df["VehicleMake"] = df["VehicleMake"].astype(str)

### Handle Invalid Future `VehicleYear` Values

**Issues Identified:**
* Presence of unrealistic future vehicle model years (e.g., year `2099` for `WorkOrderID: WO008`), noted as data entry errors.

**Cleaning Steps:**
* **Anomaly Inspection:** Filters and inspects records where `VehicleYear > 2026` alongside relevant context columns (`WorkOrderID`, `CustomerName`, `Notes`).
* **Imputation / Value Nullification:** Sets invalid future years (`> 2026`) to `np.nan` using `.loc` indexing to maintain data integrity.

In [24]:
df.loc[df["VehicleYear"] > 2026, ["WorkOrderID", "CustomerName", "VehicleYear", "Notes"]]

,WorkOrderID,CustomerName,VehicleYear,Notes
7,WO008,Miles Chatterjee,2099,"Year looks wrong, verify with customer"

In [25]:
df.loc[df["VehicleYear"] > 2026, "VehicleYear"] = np.nan

In [26]:
df["VehicleYear"].describe()

count      45.000000
mean     2013.066667
std         5.601948
min      2005.000000
25%      2008.000000
50%      2012.000000
75%      2018.000000
max      2023.000000
Name: VehicleYear, dtype: float64

### Parse and Standardize `ServiceDate`

**Issues Identified:**
* Inconsistent date formats across entries, mixing ISO format (`YYYY-MM-DD`), US format (`MM/DD/YYYY`), and abbreviated text format (`DD-Mon-YYYY`).
* Stored as a generic text (`object`) data type rather than a native datetime object.

**Cleaning Steps:**
* **Flexible Date Parsing:** Uses `pd.to_datetime()` with `format='mixed'` to automatically infer and standardize varied date string patterns into a uniform `datetime64[ns]` type.
* **Error Handling:** Sets `errors="coerce"` to safely convert unparseable or corrupted date strings into `NaT` (Not a Time) instead of halting execution.
* **Verification:** Displays the converted `ServiceDate` column to confirm proper datetime formatting across all rows.

In [27]:
df["ServiceDate"] = pd.to_datetime(df["ServiceDate"], format='mixed', errors="coerce")
df["ServiceDate"]

0    2024-04-01
1    2024-04-02
2    2024-04-02
3    2024-04-03
4    2024-04-04
5    2024-04-04
6    2024-04-05
7    2024-04-06
8    2024-04-06
9    2024-04-08
10   2024-04-09
11   2024-04-09
12   2024-04-10
13   2024-04-11
14   2024-04-11
15   2024-04-12
16   2024-04-13
17   2024-04-13
18   2024-04-15
19   2024-04-16
20   2024-04-16
21   2024-04-17
22   2024-04-18
23   2024-04-18
24   2024-04-19
25   2024-04-20
26   2024-04-20
27   2024-04-22
28   2024-04-23
29   2024-04-23
30   2024-04-24
31   2024-04-25
32   2024-04-25
33   2024-04-26
34   2024-04-27
35   2024-04-27
36   2024-04-29
37   2024-04-02
38   2024-04-30
39   2024-05-01
40   2024-05-02
41   2024-05-02
42   2024-05-03
43   2024-05-04
44   2024-05-04
45   2024-05-05
Name: ServiceDate, dtype: datetime64[us]