In [147]:
import pandas as pd

In [148]:
df = pd.read_excel('C:/Users/Junayed/pandas_prac/July_28/Customer_Call_List.xlsx')

In [149]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [150]:
df.dtypes

CustomerID            int64
First_Name              str
Last_Name               str
Phone_Number         object
Address                 str
Paying Customer         str
Do_Not_Contact          str
Not_Useful_Column      bool
dtype: object

In [151]:
df = df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [152]:
df = df.drop("Not_Useful_Column",axis=1)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [153]:
df["Last_Name"]= df["Last_Name"].str.strip("123,./_ ")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [154]:
df["Names"] = (df["First_Name"] + " " + df["Last_Name"]).str.split().str.join(" ")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Names
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,Frodo Baggins
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,Abed Nadir
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,Walter White
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,Dwight Schrute
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,Jon Snow
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,Ron Swanson
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,Jeff Winger
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,Sherlock Holmes
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,Peter Parker
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,Samwise Gamgee
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,Harry Potter
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,Don Draper
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,Leslie Knope
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,Toby Flenderson
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,Ron Weasley
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,Michael Scott
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,Clark Kent
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,Creed Braton
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,Anakin Skywalker

In [155]:
full_name = df["Names"]
target_col = df.columns.get_loc("CustomerID")
df.insert(target_col+1,"Full_Name",full_name)

In [156]:
df

,CustomerID,Full_Name,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Names
0,1001,Frodo Baggins,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,Frodo Baggins
1,1002,Abed Nadir,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,Abed Nadir
2,1003,Walter White,Walter,White,7066950392,298 Drugs Driveway,N,NaN,Walter White
3,1004,Dwight Schrute,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,Dwight Schrute
4,1005,Jon Snow,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,Jon Snow
5,1006,Ron Swanson,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,Ron Swanson
6,1007,Jeff Winger,Jeff,Winger,NaN,1209 South Street,No,No,Jeff Winger
7,1008,Sherlock Holmes,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,Sherlock Holmes
8,1009,NaN,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,NaN
9,1010,Peter Parker,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,Peter Parker
10,1011,Samwise Gamgee,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,Samwise Gamgee
11,1012,Harry Potter,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,Harry Potter
12,1013,Don Draper,Don,Draper,123-543-2345,2039 Main Street,Yes,N,Don Draper
13,1014,Leslie Knope,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,Leslie Knope
14,1015,Toby Flenderson,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,Toby Flenderson
15,1016,Ron Weasley,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,Ron Weasley
16,1017,Michael Scott,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,Michael Scott
17,1018,Clark Kent,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,Clark Kent
18,1019,Creed Braton,Creed,Braton,N/a,N/a,N/a,Yes,Creed Braton
19,1020,Anakin Skywalker,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,Anakin Skywalker

In [157]:
df = df.drop(columns=["Names","First_Name","Last_Name"])
df

,CustomerID,Full_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff Winger,NaN,1209 South Street,No,No
7,1008,Sherlock Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed Braton,N/a,N/a,N/a,Yes
19,1020,Anakin Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [158]:
df["Phone_Number"] = df["Phone_Number"].astype(str).str.replace(r'[^0-9]', '', regex=True)
df

,CustomerID,Full_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,1235455421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed Nadir,1236439775,93 West Main Street,No,Yes
2,1003,Walter White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon Snow,8766783469,123 Dragons Road,Y,No
5,1006,Ron Swanson,3047622467,768 City Parkway,Yes,Yes
6,1007,Jeff Winger,NaN,1209 South Street,No,No
7,1008,Sherlock Holmes,8766783469,98 Clue Drive,N,No
8,1009,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter Parker,1235455421,"25th Main Street, New York",Yes,No
10,1011,Samwise Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don Draper,1235432345,2039 Main Street,Yes,N
13,1014,Leslie Knope,8766783469,343 City Parkway,Yes,No
14,1015,Toby Flenderson,3047622467,214 HR Avenue,N,No
15,1016,Ron Weasley,1235455421,2395 Hogwarts Avenue,No,N
16,1017,Michael Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed Braton,,N/a,N/a,Yes
19,1020,Anakin Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N

In [159]:
df["Phone_Number"] = df["Phone_Number"].apply(lambda x: str(x))
df["Phone_Number"] = df["Phone_Number"].apply(lambda x: x[0:3] + "-" + x[3:6] + "-" + x[6:10])
df

,CustomerID,Full_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter White,706-695-0392,298 Drugs Driveway,N,NaN
3,1004,Dwight Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff Winger,nan--,1209 South Street,No,No
7,1008,Sherlock Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,NaN,--,123 Middle Earth,Yes,NaN
9,1010,Peter Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise Gamgee,nan--,"612 Shire Lane, Shire",Yes,No
11,1012,Harry Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark Kent,706-695-0392,3498 Super Lane,Y,NaN
18,1019,Creed Braton,--,N/a,N/a,Yes
19,1020,Anakin Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [163]:
df["Phone_Number"] = df["Phone_Number"].str.replace("nan--","")
df["Phone_Number"] = df["Phone_Number"].str.replace("--","")

In [164]:
df

,CustomerID,Full_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter White,706-695-0392,298 Drugs Driveway,N,NaN
3,1004,Dwight Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff Winger,,1209 South Street,No,No
7,1008,Sherlock Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark Kent,706-695-0392,3498 Super Lane,Y,NaN
18,1019,Creed Braton,,N/a,N/a,Yes
19,1020,Anakin Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [168]:
df[["Street_Address", "State", "Zip_Code"]] = df["Address"].str.split(',',n=2, expand=True)
df

,CustomerID,Full_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,NaN
1,1002,Abed Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,NaN,NaN
2,1003,Walter White,706-695-0392,298 Drugs Driveway,N,NaN,298 Drugs Driveway,NaN,NaN
3,1004,Dwight Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,NaN,NaN
5,1006,Ron Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,NaN,NaN
6,1007,Jeff Winger,,1209 South Street,No,No,1209 South Street,NaN,NaN
7,1008,Sherlock Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,NaN,NaN
8,1009,NaN,,123 Middle Earth,Yes,NaN,123 Middle Earth,NaN,NaN
9,1010,Peter Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,NaN
10,1011,Samwise Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,NaN
11,1012,Harry Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,NaN,NaN
13,1014,Leslie Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,NaN,NaN
14,1015,Toby Flenderson,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,NaN,NaN
15,1016,Ron Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,NaN
17,1018,Clark Kent,706-695-0392,3498 Super Lane,Y,NaN,3498 Super Lane,NaN,NaN
18,1019,Creed Braton,,N/a,N/a,Yes,N/a,NaN,NaN
19,1020,Anakin Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,NaN

In [170]:
street_name = df["Street_Address"]
state_name = df["State"]
zip_code = df["Zip_Code"]
target_col = df.columns.get_loc("Address")

df.insert(target_col + 1, "Street_Address", df.pop("Street_Address"))
df.insert(target_col + 2, "State", df.pop("State"))
df.insert(target_col + 3, "Zip_Code", df.pop("Zip_Code"))
df

,CustomerID,Full_Name,Phone_Number,Address,Street_Address,State,Zip_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,"123 Shire Lane, Shire",123 Shire Lane,Shire,NaN,Yes,No
1,1002,Abed Nadir,123-643-9775,93 West Main Street,93 West Main Street,NaN,NaN,No,Yes
2,1003,Walter White,706-695-0392,298 Drugs Driveway,298 Drugs Driveway,NaN,NaN,N,NaN
3,1004,Dwight Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",980 Paper Avenue,Pennsylvania,18503,Yes,Y
4,1005,Jon Snow,876-678-3469,123 Dragons Road,123 Dragons Road,NaN,NaN,Y,No
5,1006,Ron Swanson,304-762-2467,768 City Parkway,768 City Parkway,NaN,NaN,Yes,Yes
6,1007,Jeff Winger,,1209 South Street,1209 South Street,NaN,NaN,No,No
7,1008,Sherlock Holmes,876-678-3469,98 Clue Drive,98 Clue Drive,NaN,NaN,N,No
8,1009,NaN,,123 Middle Earth,123 Middle Earth,NaN,NaN,Yes,NaN
9,1010,Peter Parker,123-545-5421,"25th Main Street, New York",25th Main Street,New York,NaN,Yes,No
10,1011,Samwise Gamgee,,"612 Shire Lane, Shire",612 Shire Lane,Shire,NaN,Yes,No
11,1012,Harry Potter,706-695-0392,2394 Hogwarts Avenue,2394 Hogwarts Avenue,NaN,NaN,Y,NaN
12,1013,Don Draper,123-543-2345,2039 Main Street,2039 Main Street,NaN,NaN,Yes,N
13,1014,Leslie Knope,876-678-3469,343 City Parkway,343 City Parkway,NaN,NaN,Yes,No
14,1015,Toby Flenderson,304-762-2467,214 HR Avenue,214 HR Avenue,NaN,NaN,N,No
15,1016,Ron Weasley,123-545-5421,2395 Hogwarts Avenue,2395 Hogwarts Avenue,NaN,NaN,No,N
16,1017,Michael Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",121 Paper Avenue,Pennsylvania,NaN,Yes,No
17,1018,Clark Kent,706-695-0392,3498 Super Lane,3498 Super Lane,NaN,NaN,Y,NaN
18,1019,Creed Braton,,N/a,N/a,NaN,NaN,N/a,Yes
19,1020,Anakin Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",910 Tatooine Road,Tatooine,NaN,Yes,N

In [171]:
df = df.drop(columns= "Address")
df

,CustomerID,Full_Name,Phone_Number,Street_Address,State,Zip_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123 Shire Lane,Shire,NaN,Yes,No
1,1002,Abed Nadir,123-643-9775,93 West Main Street,NaN,NaN,No,Yes
2,1003,Walter White,706-695-0392,298 Drugs Driveway,NaN,NaN,N,NaN
3,1004,Dwight Schrute,123-543-2345,980 Paper Avenue,Pennsylvania,18503,Yes,Y
4,1005,Jon Snow,876-678-3469,123 Dragons Road,NaN,NaN,Y,No
5,1006,Ron Swanson,304-762-2467,768 City Parkway,NaN,NaN,Yes,Yes
6,1007,Jeff Winger,,1209 South Street,NaN,NaN,No,No
7,1008,Sherlock Holmes,876-678-3469,98 Clue Drive,NaN,NaN,N,No
8,1009,NaN,,123 Middle Earth,NaN,NaN,Yes,NaN
9,1010,Peter Parker,123-545-5421,25th Main Street,New York,NaN,Yes,No
10,1011,Samwise Gamgee,,612 Shire Lane,Shire,NaN,Yes,No
11,1012,Harry Potter,706-695-0392,2394 Hogwarts Avenue,NaN,NaN,Y,NaN
12,1013,Don Draper,123-543-2345,2039 Main Street,NaN,NaN,Yes,N
13,1014,Leslie Knope,876-678-3469,343 City Parkway,NaN,NaN,Yes,No
14,1015,Toby Flenderson,304-762-2467,214 HR Avenue,NaN,NaN,N,No
15,1016,Ron Weasley,123-545-5421,2395 Hogwarts Avenue,NaN,NaN,No,N
16,1017,Michael Scott,123-643-9775,121 Paper Avenue,Pennsylvania,NaN,Yes,No
17,1018,Clark Kent,706-695-0392,3498 Super Lane,NaN,NaN,Y,NaN
18,1019,Creed Braton,,N/a,NaN,NaN,N/a,Yes
19,1020,Anakin Skywalker,876-678-3469,910 Tatooine Road,Tatooine,NaN,Yes,N

In [177]:
df["State"]= df["State"].fillna("").replace("NaN","")
df

,CustomerID,Full_Name,Phone_Number,Street_Address,State,Zip_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123 Shire Lane,Shire,NaN,Yes,No
1,1002,Abed Nadir,123-643-9775,93 West Main Street,,NaN,No,Yes
2,1003,Walter White,706-695-0392,298 Drugs Driveway,,NaN,N,NaN
3,1004,Dwight Schrute,123-543-2345,980 Paper Avenue,Pennsylvania,18503,Yes,Y
4,1005,Jon Snow,876-678-3469,123 Dragons Road,,NaN,Y,No
5,1006,Ron Swanson,304-762-2467,768 City Parkway,,NaN,Yes,Yes
6,1007,Jeff Winger,,1209 South Street,,NaN,No,No
7,1008,Sherlock Holmes,876-678-3469,98 Clue Drive,,NaN,N,No
8,1009,NaN,,123 Middle Earth,,NaN,Yes,NaN
9,1010,Peter Parker,123-545-5421,25th Main Street,New York,NaN,Yes,No
10,1011,Samwise Gamgee,,612 Shire Lane,Shire,NaN,Yes,No
11,1012,Harry Potter,706-695-0392,2394 Hogwarts Avenue,,NaN,Y,NaN
12,1013,Don Draper,123-543-2345,2039 Main Street,,NaN,Yes,N
13,1014,Leslie Knope,876-678-3469,343 City Parkway,,NaN,Yes,No
14,1015,Toby Flenderson,304-762-2467,214 HR Avenue,,NaN,N,No
15,1016,Ron Weasley,123-545-5421,2395 Hogwarts Avenue,,NaN,No,N
16,1017,Michael Scott,123-643-9775,121 Paper Avenue,Pennsylvania,NaN,Yes,No
17,1018,Clark Kent,706-695-0392,3498 Super Lane,,NaN,Y,NaN
18,1019,Creed Braton,,N/a,,NaN,N/a,Yes
19,1020,Anakin Skywalker,876-678-3469,910 Tatooine Road,Tatooine,NaN,Yes,N

In [178]:
df["Zip_Code"]= df["Zip_Code"].fillna("").replace("NaN","")
df

,CustomerID,Full_Name,Phone_Number,Street_Address,State,Zip_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123 Shire Lane,Shire,,Yes,No
1,1002,Abed Nadir,123-643-9775,93 West Main Street,,,No,Yes
2,1003,Walter White,706-695-0392,298 Drugs Driveway,,,N,NaN
3,1004,Dwight Schrute,123-543-2345,980 Paper Avenue,Pennsylvania,18503,Yes,Y
4,1005,Jon Snow,876-678-3469,123 Dragons Road,,,Y,No
5,1006,Ron Swanson,304-762-2467,768 City Parkway,,,Yes,Yes
6,1007,Jeff Winger,,1209 South Street,,,No,No
7,1008,Sherlock Holmes,876-678-3469,98 Clue Drive,,,N,No
8,1009,NaN,,123 Middle Earth,,,Yes,NaN
9,1010,Peter Parker,123-545-5421,25th Main Street,New York,,Yes,No
10,1011,Samwise Gamgee,,612 Shire Lane,Shire,,Yes,No
11,1012,Harry Potter,706-695-0392,2394 Hogwarts Avenue,,,Y,NaN
12,1013,Don Draper,123-543-2345,2039 Main Street,,,Yes,N
13,1014,Leslie Knope,876-678-3469,343 City Parkway,,,Yes,No
14,1015,Toby Flenderson,304-762-2467,214 HR Avenue,,,N,No
15,1016,Ron Weasley,123-545-5421,2395 Hogwarts Avenue,,,No,N
16,1017,Michael Scott,123-643-9775,121 Paper Avenue,Pennsylvania,,Yes,No
17,1018,Clark Kent,706-695-0392,3498 Super Lane,,,Y,NaN
18,1019,Creed Braton,,N/a,,,N/a,Yes
19,1020,Anakin Skywalker,876-678-3469,910 Tatooine Road,Tatooine,,Yes,N

In [181]:
df["Paying Customer"] = df["Paying Customer"].str.replace("Yes","Y")
df["Paying Customer"] = df["Paying Customer"].str.replace("No","N")
df

,CustomerID,Full_Name,Phone_Number,Street_Address,State,Zip_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123 Shire Lane,Shire,,Y,No
1,1002,Abed Nadir,123-643-9775,93 West Main Street,,,N,Yes
2,1003,Walter White,706-695-0392,298 Drugs Driveway,,,N,NaN
3,1004,Dwight Schrute,123-543-2345,980 Paper Avenue,Pennsylvania,18503,Y,Y
4,1005,Jon Snow,876-678-3469,123 Dragons Road,,,Y,No
5,1006,Ron Swanson,304-762-2467,768 City Parkway,,,Y,Yes
6,1007,Jeff Winger,,1209 South Street,,,N,No
7,1008,Sherlock Holmes,876-678-3469,98 Clue Drive,,,N,No
8,1009,NaN,,123 Middle Earth,,,Y,NaN
9,1010,Peter Parker,123-545-5421,25th Main Street,New York,,Y,No
10,1011,Samwise Gamgee,,612 Shire Lane,Shire,,Y,No
11,1012,Harry Potter,706-695-0392,2394 Hogwarts Avenue,,,Y,NaN
12,1013,Don Draper,123-543-2345,2039 Main Street,,,Y,N
13,1014,Leslie Knope,876-678-3469,343 City Parkway,,,Y,No
14,1015,Toby Flenderson,304-762-2467,214 HR Avenue,,,N,No
15,1016,Ron Weasley,123-545-5421,2395 Hogwarts Avenue,,,N,N
16,1017,Michael Scott,123-643-9775,121 Paper Avenue,Pennsylvania,,Y,No
17,1018,Clark Kent,706-695-0392,3498 Super Lane,,,Y,NaN
18,1019,Creed Braton,,N/a,,,N/a,Yes
19,1020,Anakin Skywalker,876-678-3469,910 Tatooine Road,Tatooine,,Y,N

In [184]:
df["Street_Address"]= df["Street_Address"].str.replace("N/a","")
df["Paying Customer"]= df["Paying Customer"].str.replace("N/a","")
df

,CustomerID,Full_Name,Phone_Number,Street_Address,State,Zip_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123 Shire Lane,Shire,,Y,No
1,1002,Abed Nadir,123-643-9775,93 West Main Street,,,N,Yes
2,1003,Walter White,706-695-0392,298 Drugs Driveway,,,N,NaN
3,1004,Dwight Schrute,123-543-2345,980 Paper Avenue,Pennsylvania,18503,Y,Y
4,1005,Jon Snow,876-678-3469,123 Dragons Road,,,Y,No
5,1006,Ron Swanson,304-762-2467,768 City Parkway,,,Y,Yes
6,1007,Jeff Winger,,1209 South Street,,,N,No
7,1008,Sherlock Holmes,876-678-3469,98 Clue Drive,,,N,No
8,1009,NaN,,123 Middle Earth,,,Y,NaN
9,1010,Peter Parker,123-545-5421,25th Main Street,New York,,Y,No
10,1011,Samwise Gamgee,,612 Shire Lane,Shire,,Y,No
11,1012,Harry Potter,706-695-0392,2394 Hogwarts Avenue,,,Y,NaN
12,1013,Don Draper,123-543-2345,2039 Main Street,,,Y,N
13,1014,Leslie Knope,876-678-3469,343 City Parkway,,,Y,No
14,1015,Toby Flenderson,304-762-2467,214 HR Avenue,,,N,No
15,1016,Ron Weasley,123-545-5421,2395 Hogwarts Avenue,,,N,N
16,1017,Michael Scott,123-643-9775,121 Paper Avenue,Pennsylvania,,Y,No
17,1018,Clark Kent,706-695-0392,3498 Super Lane,,,Y,NaN
18,1019,Creed Braton,,,,,,Yes
19,1020,Anakin Skywalker,876-678-3469,910 Tatooine Road,Tatooine,,Y,N

In [186]:
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace("NaN","")
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace("No","N")
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace("Yes","Y")
df["Do_Not_Contact"] = df["Do_Not_Contact"].fillna("").replace("NaN","")
df

,CustomerID,Full_Name,Phone_Number,Street_Address,State,Zip_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123 Shire Lane,Shire,,Y,N
1,1002,Abed Nadir,123-643-9775,93 West Main Street,,,N,Y
2,1003,Walter White,706-695-0392,298 Drugs Driveway,,,N,
3,1004,Dwight Schrute,123-543-2345,980 Paper Avenue,Pennsylvania,18503,Y,Y
4,1005,Jon Snow,876-678-3469,123 Dragons Road,,,Y,N
5,1006,Ron Swanson,304-762-2467,768 City Parkway,,,Y,Y
6,1007,Jeff Winger,,1209 South Street,,,N,N
7,1008,Sherlock Holmes,876-678-3469,98 Clue Drive,,,N,N
8,1009,NaN,,123 Middle Earth,,,Y,
9,1010,Peter Parker,123-545-5421,25th Main Street,New York,,Y,N
10,1011,Samwise Gamgee,,612 Shire Lane,Shire,,Y,N
11,1012,Harry Potter,706-695-0392,2394 Hogwarts Avenue,,,Y,
12,1013,Don Draper,123-543-2345,2039 Main Street,,,Y,N
13,1014,Leslie Knope,876-678-3469,343 City Parkway,,,Y,N
14,1015,Toby Flenderson,304-762-2467,214 HR Avenue,,,N,N
15,1016,Ron Weasley,123-545-5421,2395 Hogwarts Avenue,,,N,N
16,1017,Michael Scott,123-643-9775,121 Paper Avenue,Pennsylvania,,Y,N
17,1018,Clark Kent,706-695-0392,3498 Super Lane,,,Y,
18,1019,Creed Braton,,,,,,Y
19,1020,Anakin Skywalker,876-678-3469,910 Tatooine Road,Tatooine,,Y,N

In [187]:
for x in df.index:
    if df.loc[x,"Do_Not_Contact"] == "Y":
        df.drop(x,inplace=True)

df

,CustomerID,Full_Name,Phone_Number,Street_Address,State,Zip_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123 Shire Lane,Shire,,Y,N
2,1003,Walter White,706-695-0392,298 Drugs Driveway,,,N,
4,1005,Jon Snow,876-678-3469,123 Dragons Road,,,Y,N
6,1007,Jeff Winger,,1209 South Street,,,N,N
7,1008,Sherlock Holmes,876-678-3469,98 Clue Drive,,,N,N
8,1009,NaN,,123 Middle Earth,,,Y,
9,1010,Peter Parker,123-545-5421,25th Main Street,New York,,Y,N
10,1011,Samwise Gamgee,,612 Shire Lane,Shire,,Y,N
11,1012,Harry Potter,706-695-0392,2394 Hogwarts Avenue,,,Y,
12,1013,Don Draper,123-543-2345,2039 Main Street,,,Y,N
13,1014,Leslie Knope,876-678-3469,343 City Parkway,,,Y,N
14,1015,Toby Flenderson,304-762-2467,214 HR Avenue,,,N,N
15,1016,Ron Weasley,123-545-5421,2395 Hogwarts Avenue,,,N,N
16,1017,Michael Scott,123-643-9775,121 Paper Avenue,Pennsylvania,,Y,N
17,1018,Clark Kent,706-695-0392,3498 Super Lane,,,Y,
19,1020,Anakin Skywalker,876-678-3469,910 Tatooine Road,Tatooine,,Y,N

In [188]:
for x in df.index:
    if df.loc[x,"Phone_Number"] == "":
        df.drop(x,inplace=True)

df

,CustomerID,Full_Name,Phone_Number,Street_Address,State,Zip_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123 Shire Lane,Shire,,Y,N
2,1003,Walter White,706-695-0392,298 Drugs Driveway,,,N,
4,1005,Jon Snow,876-678-3469,123 Dragons Road,,,Y,N
7,1008,Sherlock Holmes,876-678-3469,98 Clue Drive,,,N,N
9,1010,Peter Parker,123-545-5421,25th Main Street,New York,,Y,N
11,1012,Harry Potter,706-695-0392,2394 Hogwarts Avenue,,,Y,
12,1013,Don Draper,123-543-2345,2039 Main Street,,,Y,N
13,1014,Leslie Knope,876-678-3469,343 City Parkway,,,Y,N
14,1015,Toby Flenderson,304-762-2467,214 HR Avenue,,,N,N
15,1016,Ron Weasley,123-545-5421,2395 Hogwarts Avenue,,,N,N
16,1017,Michael Scott,123-643-9775,121 Paper Avenue,Pennsylvania,,Y,N
17,1018,Clark Kent,706-695-0392,3498 Super Lane,,,Y,
19,1020,Anakin Skywalker,876-678-3469,910 Tatooine Road,Tatooine,,Y,N

In [189]:
df = df.reset_index(drop=True)
df

,CustomerID,Full_Name,Phone_Number,Street_Address,State,Zip_Code,Paying Customer,Do_Not_Contact
0,1001,Frodo Baggins,123-545-5421,123 Shire Lane,Shire,,Y,N
1,1003,Walter White,706-695-0392,298 Drugs Driveway,,,N,
2,1005,Jon Snow,876-678-3469,123 Dragons Road,,,Y,N
3,1008,Sherlock Holmes,876-678-3469,98 Clue Drive,,,N,N
4,1010,Peter Parker,123-545-5421,25th Main Street,New York,,Y,N
5,1012,Harry Potter,706-695-0392,2394 Hogwarts Avenue,,,Y,
6,1013,Don Draper,123-543-2345,2039 Main Street,,,Y,N
7,1014,Leslie Knope,876-678-3469,343 City Parkway,,,Y,N
8,1015,Toby Flenderson,304-762-2467,214 HR Avenue,,,N,N
9,1016,Ron Weasley,123-545-5421,2395 Hogwarts Avenue,,,N,N
10,1017,Michael Scott,123-643-9775,121 Paper Avenue,Pennsylvania,,Y,N
11,1018,Clark Kent,706-695-0392,3498 Super Lane,,,Y,
12,1020,Anakin Skywalker,876-678-3469,910 Tatooine Road,Tatooine,,Y,N