In [207]:
import pandas as pd

In [208]:
df = pd.read_csv(r'C:\Users\Junayed\pandas_prac\July_31\messy.csv')

In [209]:
df

,CustomerID,Name,Age,SignupDate,Country,Spend,Active,Notes
0,1001,Ravi Kumar,34.0,2021-03-15,India,$245.50,Yes,NaN
1,1002,Maria Garcia,29.0,03/16/2021,Spain,312,1,Regular customer
2,1003,John Smith,NaN,2021-03-17,USA,$89.00,No,NaN
3,1004,Aisha Bello,41.0,2021-03-18,Nigeria,NaN,yes,Missing
4,1005,Chen Wei,NaN,17-03-2021,China,150.75,0,NaN
5,1006,NaN,38.0,2021-03-19,NaN,$0.00,No,NaN
6,1007,Fatima Noor,27.0,2021/03/20,Pakistan,410,Y,VIP
7,1008,Tom Wilson,52.0,2021-03-21,UK,$0,N,NaN
8,1009,Lucia Rossi,33.0,03-22-2021,Italy,275.25,yes,NaN
9,1010,David Lee,NaN,2021-03-23,South Korea,$99.99,no,Missing
10,1011,Sara Ahmed,45.0,2021-03-24,Egypt,NaN,1,NaN
11,1012,Peter Novak,NaN,2021-03-25,Czechia,$180.00,0,unknown
12,1013,Grace Mwangi,NaN,2021-03-26,Kenya,60,Yes,NaN
13,1014,Liam O'Brien,31.0,2021-03-27,Ireland,$300.10,No,NaN
14,1015,Yuki Tanaka,26.0,2021-03-28,Japan,NaN,y,VIP

In [210]:
df.shape

(15, 8)

In [211]:
df.dtypes

CustomerID      int64
Name              str
Age           float64
SignupDate        str
Country           str
Spend             str
Active            str
Notes             str
dtype: object

In [212]:
# Spend should be int64

In [213]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  15 non-null     int64
 1   Name        14 non-null     str
 2   Age         10 non-null     float64
 3   SignupDate  15 non-null     str
 4   Country     14 non-null     str
 5   Spend       12 non-null     str
 6   Active      15 non-null     str
 7   Notes       6 non-null      str
dtypes: float64(1), int64(1), str(6)
memory usage: 1.6 KB

In [214]:
df.describe(include='all')

,CustomerID,Name,Age,SignupDate,Country,Spend,Active,Notes
count,15.000000,14,10.000000,15,14,12,15,6
unique,NaN,14,NaN,15,14,12,9,4
top,NaN,Ravi Kumar,NaN,2021-03-15,India,$245.50,No,Missing
freq,NaN,1,NaN,1,1,1,3,2
mean,1008.000000,NaN,35.600000,NaN,NaN,NaN,NaN,NaN
std,4.472136,NaN,8.382521,NaN,NaN,NaN,NaN,NaN
min,1001.000000,NaN,26.000000,NaN,NaN,NaN,NaN,NaN
25%,1004.500000,NaN,29.500000,NaN,NaN,NaN,NaN,NaN
50%,1008.000000,NaN,33.500000,NaN,NaN,NaN,NaN,NaN
75%,1011.500000,NaN,40.250000,NaN,NaN,NaN,NaN,NaN
max,1015.000000,NaN,52.000000,NaN,NaN,NaN,NaN,NaN

In [215]:
df.isna().sum()

CustomerID    0
Name          1
Age           5
SignupDate    0
Country       1
Spend         3
Active        0
Notes         9
dtype: int64

In [216]:
df

,CustomerID,Name,Age,SignupDate,Country,Spend,Active,Notes
0,1001,Ravi Kumar,34.0,2021-03-15,India,$245.50,Yes,NaN
1,1002,Maria Garcia,29.0,03/16/2021,Spain,312,1,Regular customer
2,1003,John Smith,NaN,2021-03-17,USA,$89.00,No,NaN
3,1004,Aisha Bello,41.0,2021-03-18,Nigeria,NaN,yes,Missing
4,1005,Chen Wei,NaN,17-03-2021,China,150.75,0,NaN
5,1006,NaN,38.0,2021-03-19,NaN,$0.00,No,NaN
6,1007,Fatima Noor,27.0,2021/03/20,Pakistan,410,Y,VIP
7,1008,Tom Wilson,52.0,2021-03-21,UK,$0,N,NaN
8,1009,Lucia Rossi,33.0,03-22-2021,Italy,275.25,yes,NaN
9,1010,David Lee,NaN,2021-03-23,South Korea,$99.99,no,Missing
10,1011,Sara Ahmed,45.0,2021-03-24,Egypt,NaN,1,NaN
11,1012,Peter Novak,NaN,2021-03-25,Czechia,$180.00,0,unknown
12,1013,Grace Mwangi,NaN,2021-03-26,Kenya,60,Yes,NaN
13,1014,Liam O'Brien,31.0,2021-03-27,Ireland,$300.10,No,NaN
14,1015,Yuki Tanaka,26.0,2021-03-28,Japan,NaN,y,VIP

In [217]:
df[df['Name']!=""]

,CustomerID,Name,Age,SignupDate,Country,Spend,Active,Notes
0,1001,Ravi Kumar,34.0,2021-03-15,India,$245.50,Yes,NaN
1,1002,Maria Garcia,29.0,03/16/2021,Spain,312,1,Regular customer
2,1003,John Smith,NaN,2021-03-17,USA,$89.00,No,NaN
3,1004,Aisha Bello,41.0,2021-03-18,Nigeria,NaN,yes,Missing
4,1005,Chen Wei,NaN,17-03-2021,China,150.75,0,NaN
5,1006,NaN,38.0,2021-03-19,NaN,$0.00,No,NaN
6,1007,Fatima Noor,27.0,2021/03/20,Pakistan,410,Y,VIP
7,1008,Tom Wilson,52.0,2021-03-21,UK,$0,N,NaN
8,1009,Lucia Rossi,33.0,03-22-2021,Italy,275.25,yes,NaN
9,1010,David Lee,NaN,2021-03-23,South Korea,$99.99,no,Missing
10,1011,Sara Ahmed,45.0,2021-03-24,Egypt,NaN,1,NaN
11,1012,Peter Novak,NaN,2021-03-25,Czechia,$180.00,0,unknown
12,1013,Grace Mwangi,NaN,2021-03-26,Kenya,60,Yes,NaN
13,1014,Liam O'Brien,31.0,2021-03-27,Ireland,$300.10,No,NaN
14,1015,Yuki Tanaka,26.0,2021-03-28,Japan,NaN,y,VIP

In [218]:
df['SignupDate'] = pd.to_datetime(df['SignupDate'],format='mixed')

In [219]:
df["SignupDate"] = pd.to_datetime(df["SignupDate"]).dt.strftime("%Y-%m-%d")

In [220]:
df

,CustomerID,Name,Age,SignupDate,Country,Spend,Active,Notes
0,1001,Ravi Kumar,34.0,2021-03-15,India,$245.50,Yes,NaN
1,1002,Maria Garcia,29.0,2021-03-16,Spain,312,1,Regular customer
2,1003,John Smith,NaN,2021-03-17,USA,$89.00,No,NaN
3,1004,Aisha Bello,41.0,2021-03-18,Nigeria,NaN,yes,Missing
4,1005,Chen Wei,NaN,2021-03-17,China,150.75,0,NaN
5,1006,NaN,38.0,2021-03-19,NaN,$0.00,No,NaN
6,1007,Fatima Noor,27.0,2021-03-20,Pakistan,410,Y,VIP
7,1008,Tom Wilson,52.0,2021-03-21,UK,$0,N,NaN
8,1009,Lucia Rossi,33.0,2021-03-22,Italy,275.25,yes,NaN
9,1010,David Lee,NaN,2021-03-23,South Korea,$99.99,no,Missing
10,1011,Sara Ahmed,45.0,2021-03-24,Egypt,NaN,1,NaN
11,1012,Peter Novak,NaN,2021-03-25,Czechia,$180.00,0,unknown
12,1013,Grace Mwangi,NaN,2021-03-26,Kenya,60,Yes,NaN
13,1014,Liam O'Brien,31.0,2021-03-27,Ireland,$300.10,No,NaN
14,1015,Yuki Tanaka,26.0,2021-03-28,Japan,NaN,y,VIP

In [221]:
df = df[df["Name"].notna()]

In [222]:
df = df[df["Spend"].notna()]

In [223]:
df

,CustomerID,Name,Age,SignupDate,Country,Spend,Active,Notes
0,1001,Ravi Kumar,34.0,2021-03-15,India,$245.50,Yes,NaN
1,1002,Maria Garcia,29.0,2021-03-16,Spain,312,1,Regular customer
2,1003,John Smith,NaN,2021-03-17,USA,$89.00,No,NaN
4,1005,Chen Wei,NaN,2021-03-17,China,150.75,0,NaN
6,1007,Fatima Noor,27.0,2021-03-20,Pakistan,410,Y,VIP
7,1008,Tom Wilson,52.0,2021-03-21,UK,$0,N,NaN
8,1009,Lucia Rossi,33.0,2021-03-22,Italy,275.25,yes,NaN
9,1010,David Lee,NaN,2021-03-23,South Korea,$99.99,no,Missing
11,1012,Peter Novak,NaN,2021-03-25,Czechia,$180.00,0,unknown
12,1013,Grace Mwangi,NaN,2021-03-26,Kenya,60,Yes,NaN
13,1014,Liam O'Brien,31.0,2021-03-27,Ireland,$300.10,No,NaN

In [224]:
active_map = {
    "Yes": "Yes", "yes": "Yes", "Y": "Yes", "y": "Yes", "1": "Yes", 1: "Yes",
    "No": "No", "no": "No", "N": "No", "n": "No", "0": "No", 0: "No"
}

df['Active'] = df['Active'].map(active_map)

In [225]:
df

,CustomerID,Name,Age,SignupDate,Country,Spend,Active,Notes
0,1001,Ravi Kumar,34.0,2021-03-15,India,$245.50,Yes,NaN
1,1002,Maria Garcia,29.0,2021-03-16,Spain,312,Yes,Regular customer
2,1003,John Smith,NaN,2021-03-17,USA,$89.00,No,NaN
4,1005,Chen Wei,NaN,2021-03-17,China,150.75,No,NaN
6,1007,Fatima Noor,27.0,2021-03-20,Pakistan,410,Yes,VIP
7,1008,Tom Wilson,52.0,2021-03-21,UK,$0,No,NaN
8,1009,Lucia Rossi,33.0,2021-03-22,Italy,275.25,Yes,NaN
9,1010,David Lee,NaN,2021-03-23,South Korea,$99.99,No,Missing
11,1012,Peter Novak,NaN,2021-03-25,Czechia,$180.00,No,unknown
12,1013,Grace Mwangi,NaN,2021-03-26,Kenya,60,Yes,NaN
13,1014,Liam O'Brien,31.0,2021-03-27,Ireland,$300.10,No,NaN

In [226]:
df['Spend'] = df['Spend'].astype(str).str.replace("$","", regex=False).str.strip()

In [227]:
df['Spend'] = pd.to_numeric(df['Spend'], errors = "coerce")
df['Spend'] = df['Spend'].map("${:,.2f}".format)

In [228]:
df

,CustomerID,Name,Age,SignupDate,Country,Spend,Active,Notes
0,1001,Ravi Kumar,34.0,2021-03-15,India,$245.50,Yes,NaN
1,1002,Maria Garcia,29.0,2021-03-16,Spain,$312.00,Yes,Regular customer
2,1003,John Smith,NaN,2021-03-17,USA,$89.00,No,NaN
4,1005,Chen Wei,NaN,2021-03-17,China,$150.75,No,NaN
6,1007,Fatima Noor,27.0,2021-03-20,Pakistan,$410.00,Yes,VIP
7,1008,Tom Wilson,52.0,2021-03-21,UK,$0.00,No,NaN
8,1009,Lucia Rossi,33.0,2021-03-22,Italy,$275.25,Yes,NaN
9,1010,David Lee,NaN,2021-03-23,South Korea,$99.99,No,Missing
11,1012,Peter Novak,NaN,2021-03-25,Czechia,$180.00,No,unknown
12,1013,Grace Mwangi,NaN,2021-03-26,Kenya,$60.00,Yes,NaN
13,1014,Liam O'Brien,31.0,2021-03-27,Ireland,$300.10,No,NaN

In [229]:
df['Notes'].value_counts()

Notes
Regular customer    1
VIP                 1
Missing             1
unknown             1
Name: count, dtype: int64

In [230]:
import numpy as np

df["Notes"] = df["Notes"].astype(str).str.strip()

df["Notes"] = df["Notes"].replace(
    ["unknown", "Missing", "missing", "nan", "NaN"], np.nan
)

df["Notes"] = df["Notes"].replace({"Regular customer": "Regular"})

In [231]:
df["Notes"] = df["Notes"].fillna("Not Available")

In [232]:
df

,CustomerID,Name,Age,SignupDate,Country,Spend,Active,Notes
0,1001,Ravi Kumar,34.0,2021-03-15,India,$245.50,Yes,Not Available
1,1002,Maria Garcia,29.0,2021-03-16,Spain,$312.00,Yes,Regular
2,1003,John Smith,NaN,2021-03-17,USA,$89.00,No,Not Available
4,1005,Chen Wei,NaN,2021-03-17,China,$150.75,No,Not Available
6,1007,Fatima Noor,27.0,2021-03-20,Pakistan,$410.00,Yes,VIP
7,1008,Tom Wilson,52.0,2021-03-21,UK,$0.00,No,Not Available
8,1009,Lucia Rossi,33.0,2021-03-22,Italy,$275.25,Yes,Not Available
9,1010,David Lee,NaN,2021-03-23,South Korea,$99.99,No,Not Available
11,1012,Peter Novak,NaN,2021-03-25,Czechia,$180.00,No,Not Available
12,1013,Grace Mwangi,NaN,2021-03-26,Kenya,$60.00,Yes,Not Available
13,1014,Liam O'Brien,31.0,2021-03-27,Ireland,$300.10,No,Not Available

In [233]:
df['Age'] = df['Age'].fillna("")

In [234]:
df

,CustomerID,Name,Age,SignupDate,Country,Spend,Active,Notes
0,1001,Ravi Kumar,34.0,2021-03-15,India,$245.50,Yes,Not Available
1,1002,Maria Garcia,29.0,2021-03-16,Spain,$312.00,Yes,Regular
2,1003,John Smith,,2021-03-17,USA,$89.00,No,Not Available
4,1005,Chen Wei,,2021-03-17,China,$150.75,No,Not Available
6,1007,Fatima Noor,27.0,2021-03-20,Pakistan,$410.00,Yes,VIP
7,1008,Tom Wilson,52.0,2021-03-21,UK,$0.00,No,Not Available
8,1009,Lucia Rossi,33.0,2021-03-22,Italy,$275.25,Yes,Not Available
9,1010,David Lee,,2021-03-23,South Korea,$99.99,No,Not Available
11,1012,Peter Novak,,2021-03-25,Czechia,$180.00,No,Not Available
12,1013,Grace Mwangi,,2021-03-26,Kenya,$60.00,Yes,Not Available
13,1014,Liam O'Brien,31.0,2021-03-27,Ireland,$300.10,No,Not Available

In [235]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [236]:
df

,CustomerID,Name,Age,SignupDate,Country,Spend,Active,Notes
0,1001,Ravi Kumar,34.0,2021-03-15,India,$245.50,Yes,Not Available
1,1002,Maria Garcia,29.0,2021-03-16,Spain,$312.00,Yes,Regular
2,1003,John Smith,NaN,2021-03-17,USA,$89.00,No,Not Available
4,1005,Chen Wei,NaN,2021-03-17,China,$150.75,No,Not Available
6,1007,Fatima Noor,27.0,2021-03-20,Pakistan,$410.00,Yes,VIP
7,1008,Tom Wilson,52.0,2021-03-21,UK,$0.00,No,Not Available
8,1009,Lucia Rossi,33.0,2021-03-22,Italy,$275.25,Yes,Not Available
9,1010,David Lee,NaN,2021-03-23,South Korea,$99.99,No,Not Available
11,1012,Peter Novak,NaN,2021-03-25,Czechia,$180.00,No,Not Available
12,1013,Grace Mwangi,NaN,2021-03-26,Kenya,$60.00,Yes,Not Available
13,1014,Liam O'Brien,31.0,2021-03-27,Ireland,$300.10,No,Not Available

In [237]:
df.to_excel("Cleaned.xlsx", index=False)