In [48]:
import pandas as pd

In [49]:
df = pd.read_csv(r'C:\Users\Junayed\pandas_prac\Aug-1\messy_aug1.csv')

In [50]:
df

,OrderID,Customer,Qty,UnitPrice,Discount,OrderDate,Status,Comment
0,5001,Priya Shah,3.0,$45.00,10%,2022-01-05,shipped,NaN
1,5002,Omar Haddad,NaN,$12.50,0%,01/06/2022,Shipped,Regular buyer
2,5003,Nina Petrova,5.0,60,NaN,2022-01-07,PENDING,NaN
3,5004,NaN,2.0,$8.99,5%,2022-01-08,shipped,VIP
4,5005,Marcus Lee,1.0,$150.00,0%,07-01-2022,cancelled,NaN
5,5006,Nina Petrova,5.0,$60.00,NaN,2022-01-07,pending,Duplicate?
6,5007,Ines Duarte,4.0,NaN,10%,2022-01-09,Shipped,NaN
7,5008,Tariq Ahmed,NaN,$22.00,0%,2022-01-10,shipped,unknown
8,5009,Wei Zhang,2.0,$99.00,20%,10/01/2022,Cancelled,NaN
9,5010,Jonas Berg,3.0,$30.50,0%,2022-01-11,shipped,NaN
10,5011,Sofia Reyes,NaN,$0.00,0%,2022-01-12,pending,Missing
11,5012,Aiden Clarke,6.0,$18.25,5%,12-01-2022,shipped,NaN
12,5013,NaN,3.0,$45.00,10%,2022-01-05,shipped,Duplicate?
13,5014,Hana Kobayashi,2.0,$75.00,NaN,2022-01-13,SHIPPED,NaN
14,5015,Leo Fischer,1.0,$40.00,0%,2022-01-14,pending,VIP

In [51]:
print('Shape:',df.shape)
print('Data Type:')
df.dtypes

Shape: (15, 8)
Data Type:

OrderID        int64
Customer         str
Qty          float64
UnitPrice        str
Discount         str
OrderDate        str
Status           str
Comment          str
dtype: object

In [52]:
df['Qty'] = df['Qty'].astype("Int64")
df['Qty']

0        3
1     <NA>
2        5
3        2
4        1
5        5
6        4
7     <NA>
8        2
9        3
10    <NA>
11       6
12       3
13       2
14       1
Name: Qty, dtype: Int64

In [53]:
df['UnitPrice'] = df['UnitPrice'].astype(str).str.replace("$","",regex=False).str.strip()

df['UnitPrice'] = pd.to_numeric(df['UnitPrice'], errors='coerce')

df['UnitPrice']

0      45.00
1      12.50
2      60.00
3       8.99
4     150.00
5      60.00
6        NaN
7      22.00
8      99.00
9      30.50
10      0.00
11     18.25
12     45.00
13     75.00
14     40.00
Name: UnitPrice, dtype: float64

In [54]:
df['Discount'] = df['Discount'].astype(str).str.replace("%","",regex=False).str.strip()

df['Discount'] = pd.to_numeric(df['Discount'], errors='coerce') / 100

df['Discount']

0     0.10
1     0.00
2      NaN
3     0.05
4     0.00
5      NaN
6     0.10
7     0.00
8     0.20
9     0.00
10    0.00
11    0.05
12    0.10
13     NaN
14    0.00
Name: Discount, dtype: float64

In [55]:
df['OrderDate'] = pd.to_datetime(df['OrderDate'], format='mixed')

In [56]:
df['Status'] = df['Status'].astype(str).str.strip().str.title()

df['Status']

0       Shipped
1       Shipped
2       Pending
3       Shipped
4     Cancelled
5       Pending
6       Shipped
7       Shipped
8     Cancelled
9       Shipped
10      Pending
11      Shipped
12      Shipped
13      Shipped
14      Pending
Name: Status, dtype: str

In [57]:
df['Status'].value_counts()

Status
Shipped      9
Pending      4
Cancelled    2
Name: count, dtype: int64

In [58]:
import numpy as np
df['Comment'] = df['Comment'].astype(str).str.strip()

df['Comment'] = df['Comment'].replace(['unknown','Missing','None','nan'],np.nan)

In [59]:
df['Comment']

0               NaN
1     Regular buyer
2               NaN
3               VIP
4               NaN
5        Duplicate?
6               NaN
7               NaN
8               NaN
9               NaN
10              NaN
11              NaN
12       Duplicate?
13              NaN
14              VIP
Name: Comment, dtype: str

In [60]:
sub_set = ["Qty","UnitPrice","Discount","OrderDate"]

dup_chk = df.duplicated(sub_set, keep=False)
df[dup_chk]

,OrderID,Customer,Qty,UnitPrice,Discount,OrderDate,Status,Comment
0,5001,Priya Shah,3,45.0,0.1,2022-01-05,Shipped,NaN
2,5003,Nina Petrova,5,60.0,NaN,2022-01-07,Pending,NaN
5,5006,Nina Petrova,5,60.0,NaN,2022-01-07,Pending,Duplicate?
12,5013,NaN,3,45.0,0.1,2022-01-05,Shipped,Duplicate?

In [61]:
df = df[~df['OrderID'].isin([5006,5013])]

In [62]:
df['Customer'] = df['Customer'].fillna("Unknown")
df.reset_index(drop=True)

,OrderID,Customer,Qty,UnitPrice,Discount,OrderDate,Status,Comment
0,5001,Priya Shah,3,45.00,0.10,2022-01-05,Shipped,NaN
1,5002,Omar Haddad,<NA>,12.50,0.00,2022-01-06,Shipped,Regular buyer
2,5003,Nina Petrova,5,60.00,NaN,2022-01-07,Pending,NaN
3,5004,Unknown,2,8.99,0.05,2022-01-08,Shipped,VIP
4,5005,Marcus Lee,1,150.00,0.00,2022-07-01,Cancelled,NaN
5,5007,Ines Duarte,4,NaN,0.10,2022-01-09,Shipped,NaN
6,5008,Tariq Ahmed,<NA>,22.00,0.00,2022-01-10,Shipped,NaN
7,5009,Wei Zhang,2,99.00,0.20,2022-10-01,Cancelled,NaN
8,5010,Jonas Berg,3,30.50,0.00,2022-01-11,Shipped,NaN
9,5011,Sofia Reyes,<NA>,0.00,0.00,2022-01-12,Pending,NaN
10,5012,Aiden Clarke,6,18.25,0.05,2022-12-01,Shipped,NaN
11,5014,Hana Kobayashi,2,75.00,NaN,2022-01-13,Shipped,NaN
12,5015,Leo Fischer,1,40.00,0.00,2022-01-14,Pending,VIP

In [63]:
df['Discount'] = df['Discount'].fillna(0)

df['Discount']

0     0.10
1     0.00
2     0.00
3     0.05
4     0.00
6     0.10
7     0.00
8     0.20
9     0.00
10    0.00
11    0.05
13    0.00
14    0.00
Name: Discount, dtype: float64

In [64]:
df['Final Price'] = (df['Qty']*df['UnitPrice']) * (1- df['Discount'])

In [65]:
target_col = df.columns.get_loc("Discount")
df.insert(target_col + 1, "Final Price", df.pop("Final Price"))

In [66]:
df

,OrderID,Customer,Qty,UnitPrice,Discount,Final Price,OrderDate,Status,Comment
0,5001,Priya Shah,3,45.00,0.10,121.5,2022-01-05,Shipped,NaN
1,5002,Omar Haddad,<NA>,12.50,0.00,<NA>,2022-01-06,Shipped,Regular buyer
2,5003,Nina Petrova,5,60.00,0.00,300.0,2022-01-07,Pending,NaN
3,5004,Unknown,2,8.99,0.05,17.081,2022-01-08,Shipped,VIP
4,5005,Marcus Lee,1,150.00,0.00,150.0,2022-07-01,Cancelled,NaN
6,5007,Ines Duarte,4,NaN,0.10,<NA>,2022-01-09,Shipped,NaN
7,5008,Tariq Ahmed,<NA>,22.00,0.00,<NA>,2022-01-10,Shipped,NaN
8,5009,Wei Zhang,2,99.00,0.20,158.4,2022-10-01,Cancelled,NaN
9,5010,Jonas Berg,3,30.50,0.00,91.5,2022-01-11,Shipped,NaN
10,5011,Sofia Reyes,<NA>,0.00,0.00,<NA>,2022-01-12,Pending,NaN
11,5012,Aiden Clarke,6,18.25,0.05,104.025,2022-12-01,Shipped,NaN
13,5014,Hana Kobayashi,2,75.00,0.00,150.0,2022-01-13,Shipped,NaN
14,5015,Leo Fischer,1,40.00,0.00,40.0,2022-01-14,Pending,VIP

In [67]:
df.dtypes

OrderID                 int64
Customer                  str
Qty                     Int64
UnitPrice             float64
Discount              float64
Final Price           Float64
OrderDate      datetime64[us]
Status                    str
Comment                   str
dtype: object

In [68]:
df.isna().sum()

OrderID         0
Customer        0
Qty             3
UnitPrice       1
Discount        0
Final Price     4
OrderDate       0
Status          0
Comment        10
dtype: int64

In [71]:
df.to_excel("Cleaned_data.xlsx", index=False)