In [37]:
import pandas as pd
import re
import numpy as np
import matplotlib.pyplot as plt

In [38]:
df = pd.read_csv(r"C:\Users\Junayed\pandas_prac\Sept\Sept_18\messy_coworking_day16.csv")

In [39]:
df.head(5)

,BookingID,MemberName,MemberEmail,MemberPhone,MembershipTier,Branch,BookingDate,DeskType,CheckInMethod,HoursBooked,AmenitiesUsed,Rating,PaymentStatus,AmountBilled,Notes
0,B001,Talia Bregman,talia.bregman@mail.com,(415) 555-0161,basic,downtown hub,06/01/2024,hot desk,mobile app,120 min,NaN,5 stars,Paid,16.0,NaN
1,B002,desmond okafor,desmond.okafor@mail.com,415-555-0172,STANDARD,Riverside Hub,06/02/2024,Dedicated Desk,key card,8,Phone Booth,5/5,Paid,48.0,NaN
2,B003,Rosalind Fenwick,rosalind.fenwick@mail.com,(510) 555-0183,Premiun,UPTOWN HUB,03-Jun-2024,Private Office,Front Desk,6 hrs,"Whiteboard, Locker, Meeting Room",4/5,paid,24.0,NaN
3,B004,Kwame Asante,kwame.asante@@mail.com,510.555.0194,basic,Downtown Hub,06/04/2024,hot desk,mobile app,5h,NaN,4,PAID,40.0,NaN
4,B005,VIOLA MARCHETTI,viola.marchetti@mail.com,(628) 555-0105,standard,Riverside Hub,06/05/2024,dedicated desk,Key Card,3,"Whiteboard, Printer, Coffee",5 stars,paid,18.0,NaN

In [40]:
df.shape

(50, 15)

In [41]:
df.dtypes

BookingID             str
MemberName            str
MemberEmail           str
MemberPhone           str
MembershipTier        str
Branch                str
BookingDate           str
DeskType              str
CheckInMethod         str
HoursBooked           str
AmenitiesUsed         str
Rating                str
PaymentStatus         str
AmountBilled      float64
Notes                 str
dtype: object

In [42]:
rates = pd.read_csv(r"C:\Users\Junayed\pandas_prac\Sept\Sept_18\membership_rates_day16.csv")
rates

  MembershipTier  HourlyRate
0          Basic           8
1       Standard           6
2        Premium           4

### Clean Member Names
- Converted column values to text (`astype(str)`)
- Removed leading and trailing whitespace (`strip()`)
- Formatted names into Title Case (`title()`)

In [43]:
df["MemberName"] = df["MemberName"].astype(str).str.strip().str.title()
df["MemberName"]

0         Talia Bregman
1        Desmond Okafor
2      Rosalind Fenwick
3          Kwame Asante
4       Viola Marchetti
5        Ezra Lindqvist
6     Priyanka Deshmukh
7          Hugo Santoro
8          Amara Chukwu
9        Bertrand Okoye
10           Selin Kaya
11       Marcus Feldman
12      Odalys Quintero
13     Nikolai Petrenko
14      Fatima Al-Sayed
15     Gideon Westbrook
16     Camille Duvalier
17      Tobias Reinholt
18    Aiyana Whitehorse
19     Rafael Contreras
20           Selin Kaya
21     Winifred Asplund
22         Idris Mwangi
23       Noor Hendricks
24       Callista Reyes
25        Talia Bregman
26       Desmond Okafor
27     Rosalind Fenwick
28         Kwame Asante
29      Viola Marchetti
30       Ezra Lindqvist
31    Priyanka Deshmukh
32         Hugo Santoro
33         Amara Chukwu
34       Bertrand Okoye
35           Selin Kaya
36       Marcus Feldman
37      Odalys Quintero
38     Nikolai Petrenko
39      Fatima Al-Sayed
40     Gideon Westbrook
41     Camille Duvalier
42      Tobias Reinholt
43    Aiyana Whitehorse
44     Rafael Contreras
45           Selin Kaya
46       Ezra Lindqvist
47         Idris Mwangi
48       Noor Hendricks
49       Callista Reyes
Name: MemberName, dtype: str

In [44]:
df['MemberEmail'].isna().sum()

np.int64(2)

### Validate Email Format
- Defined a **regex pattern** to check for valid email structures
- Used `.str.match()` to test each email against the pattern
- Filtered to find rows where the email **failed** the check (`~valid_email`) but is not missing

In [45]:
email_pattern = r'^[\w.\-]+@[\w\-]+\.[a-zA-Z]{2,}$'
valid_email = df["MemberEmail"].str.match(email_pattern, na=False)
df.loc[~valid_email & df["MemberEmail"].notna(), ["BookingID", "MemberName", "MemberEmail"]]

   BookingID    MemberName             MemberEmail
3       B004  Kwame Asante  kwame.asante@@mail.com
8       B009  Amara Chukwu       amara.chukwu@mail
28      B029  Kwame Asante  kwame.asante@@mail.com
33      B034  Amara Chukwu       amara.chukwu@mail

### Update Emails for Specific Booking IDs
- Used `.isin()` to select rows matching a list of Booking IDs
- Assigned corresponding email addresses to the `MemberEmail` column

In [46]:
df.loc[df["BookingID"].isin(["B004","B009","B029","B034"]), "MemberEmail"] = ["kwame.asante@mail.com","amara.chukwu@mail.com", "kwame.asante@mail.com","amara.chukwu@mail.com"]

### Clean Phone Numbers
- Converted values to strings and removed non-digit characters (`re.sub(r"\D", ...)`)
- Formatted 10-digit numbers into standard format (`XXX-XXX-XXXX`)
- Handled missing values gracefully (`pd.isna` and `np.nan`)

In [47]:
def clean_phone(val):
    if pd.isna(val):
        return np.nan
    digits = re.sub(r"\D", "", str(val))
    if len(digits) == 10:
        return f"{digits[0:3]}-{digits[3:6]}-{digits[6:10]}"
    return np.nan

df["MemberPhone"] = df["MemberPhone"].apply(clean_phone)
df["MemberPhone"]

0     415-555-0161
1     415-555-0172
2     510-555-0183
3     510-555-0194
4     628-555-0105
5     628-555-0116
6     415-555-0127
7              NaN
8     510-555-0139
9     510-555-0140
10    628-555-0151
11    628-555-0162
12    415-555-0173
13             NaN
14    510-555-0184
15    510-555-0195
16    628-555-0106
17    628-555-0117
18    415-555-0128
19    415-555-0139
20    628-555-0151
21    510-555-0142
22    510-555-0153
23    628-555-0164
24    628-555-0175
25    415-555-0161
26    415-555-0172
27    510-555-0183
28    510-555-0194
29    628-555-0105
30    628-555-0116
31    415-555-0127
32             NaN
33    510-555-0139
34    510-555-0140
35    628-555-0151
36    628-555-0162
37    415-555-0173
38             NaN
39    510-555-0184
40    510-555-0195
41    628-555-0106
42    628-555-0117
43    415-555-0128
44    415-555-0139
45    628-555-0151
46             NaN
47    510-555-0153
48    628-555-0164
49    628-555-0175
Name: MemberPhone, dtype: str

In [48]:
df["MembershipTier"].value_counts()

MembershipTier
STANDARD    9
Basic       8
Premiun     7
Premium     6
basic       5
standard    4
BASIC       4
Standard    4
premium     3
Name: count, dtype: int64

## Fix MembershipTier
 
| Step | Code | Description |
|------|------|-------------|
| 1 | `correct_word = {...}` | Dictionary mapping misspelled values to their correct spelling (`"Premiun"` → `"Premium"`) |
| 2 | `.astype(str)` | Converts the `MembershipTier` column to string type to allow string operations |
| 3 | `.str.replace(correct_word)` | Replaces the misspelled values using the correction dictionary |
| 4 | `.str.title()` | Standardizes capitalization (e.g., `"premium"` → `"Premium"`) |
| 5 | `.value_counts()` | Displays the count of each unique membership tier to verify the cleaning |
 
## Result
 
- Fixes the typo `"Premiun"` → `"Premium"`
- All tier names are normalized to Title Case
- Final value counts confirm the cleaned categories

In [49]:
correct_word = {
    "Premiun" : "Premium"
}

df["MembershipTier"] = df["MembershipTier"].astype(str).str.replace(correct_word).str.title()
df["MembershipTier"].value_counts()

MembershipTier
Basic       17
Standard    17
Premium     16
Name: count, dtype: int64