In [28]:
import pandas as pd
import re
import numpy as np
import matplotlib.pyplot as plt

In [29]:
df = pd.read_csv(r"C:\Users\Junayed\pandas_prac\Sept\Sept_18\messy_coworking_day16.csv")

In [30]:
df.head(5)

,BookingID,MemberName,MemberEmail,MemberPhone,MembershipTier,Branch,BookingDate,DeskType,CheckInMethod,HoursBooked,AmenitiesUsed,Rating,PaymentStatus,AmountBilled,Notes
0,B001,Talia Bregman,talia.bregman@mail.com,(415) 555-0161,basic,downtown hub,06/01/2024,hot desk,mobile app,120 min,NaN,5 stars,Paid,16.0,NaN
1,B002,desmond okafor,desmond.okafor@mail.com,415-555-0172,STANDARD,Riverside Hub,06/02/2024,Dedicated Desk,key card,8,Phone Booth,5/5,Paid,48.0,NaN
2,B003,Rosalind Fenwick,rosalind.fenwick@mail.com,(510) 555-0183,Premiun,UPTOWN HUB,03-Jun-2024,Private Office,Front Desk,6 hrs,"Whiteboard, Locker, Meeting Room",4/5,paid,24.0,NaN
3,B004,Kwame Asante,kwame.asante@@mail.com,510.555.0194,basic,Downtown Hub,06/04/2024,hot desk,mobile app,5h,NaN,4,PAID,40.0,NaN
4,B005,VIOLA MARCHETTI,viola.marchetti@mail.com,(628) 555-0105,standard,Riverside Hub,06/05/2024,dedicated desk,Key Card,3,"Whiteboard, Printer, Coffee",5 stars,paid,18.0,NaN

In [31]:
df.shape

(50, 15)

In [32]:
df.dtypes

BookingID             str
MemberName            str
MemberEmail           str
MemberPhone           str
MembershipTier        str
Branch                str
BookingDate           str
DeskType              str
CheckInMethod         str
HoursBooked           str
AmenitiesUsed         str
Rating                str
PaymentStatus         str
AmountBilled      float64
Notes                 str
dtype: object

In [33]:
rates = pd.read_csv(r"C:\Users\Junayed\pandas_prac\Sept\Sept_18\membership_rates_day16.csv")
rates

  MembershipTier  HourlyRate
0          Basic           8
1       Standard           6
2        Premium           4

### Clean Member Names
- Converted column values to text (`astype(str)`)
- Removed leading and trailing whitespace (`strip()`)
- Formatted names into Title Case (`title()`)

In [34]:
df["MemberName"] = df["MemberName"].astype(str).str.strip().str.title()
df["MemberName"]

0         Talia Bregman
1        Desmond Okafor
2      Rosalind Fenwick
3          Kwame Asante
4       Viola Marchetti
5        Ezra Lindqvist
6     Priyanka Deshmukh
7          Hugo Santoro
8          Amara Chukwu
9        Bertrand Okoye
10           Selin Kaya
11       Marcus Feldman
12      Odalys Quintero
13     Nikolai Petrenko
14      Fatima Al-Sayed
15     Gideon Westbrook
16     Camille Duvalier
17      Tobias Reinholt
18    Aiyana Whitehorse
19     Rafael Contreras
20           Selin Kaya
21     Winifred Asplund
22         Idris Mwangi
23       Noor Hendricks
24       Callista Reyes
25        Talia Bregman
26       Desmond Okafor
27     Rosalind Fenwick
28         Kwame Asante
29      Viola Marchetti
30       Ezra Lindqvist
31    Priyanka Deshmukh
32         Hugo Santoro
33         Amara Chukwu
34       Bertrand Okoye
35           Selin Kaya
36       Marcus Feldman
37      Odalys Quintero
38     Nikolai Petrenko
39      Fatima Al-Sayed
40     Gideon Westbrook
41     Camille Duvalier
42      Tobias Reinholt
43    Aiyana Whitehorse
44     Rafael Contreras
45           Selin Kaya
46       Ezra Lindqvist
47         Idris Mwangi
48       Noor Hendricks
49       Callista Reyes
Name: MemberName, dtype: str

In [35]:
df['MemberEmail'].isna().sum()

np.int64(2)

### Validate Email Format
- Defined a **regex pattern** to check for valid email structures
- Used `.str.match()` to test each email against the pattern
- Filtered to find rows where the email **failed** the check (`~valid_email`) but is not missing

In [36]:
email_pattern = r'^[\w.\-]+@[\w\-]+\.[a-zA-Z]{2,}$'
valid_email = df["MemberEmail"].str.match(email_pattern, na=False)
df.loc[~valid_email & df["MemberEmail"].notna(), ["BookingID", "MemberName", "MemberEmail"]]

   BookingID    MemberName             MemberEmail
3       B004  Kwame Asante  kwame.asante@@mail.com
8       B009  Amara Chukwu       amara.chukwu@mail
28      B029  Kwame Asante  kwame.asante@@mail.com
33      B034  Amara Chukwu       amara.chukwu@mail

### Update Emails for Specific Booking IDs
- Used `.isin()` to select rows matching a list of Booking IDs
- Assigned corresponding email addresses to the `MemberEmail` column

In [37]:
df.loc[df["BookingID"].isin(["B004","B009","B029","B034"]), "MemberEmail"] = ["kwame.asante@mail.com","amara.chukwu@mail.com", "kwame.asante@mail.com","amara.chukwu@mail.com"]

### Clean Phone Numbers
- Converted values to strings and removed non-digit characters (`re.sub(r"\D", ...)`)
- Formatted 10-digit numbers into standard format (`XXX-XXX-XXXX`)
- Handled missing values gracefully (`pd.isna` and `np.nan`)

In [38]:
def clean_phone(val):
    if pd.isna(val):
        return np.nan
    digits = re.sub(r"\D", "", str(val))
    if len(digits) == 10:
        return f"{digits[0:3]}-{digits[3:6]}-{digits[6:10]}"
    return np.nan

df["MemberPhone"] = df["MemberPhone"].apply(clean_phone)
df["MemberPhone"]

0     415-555-0161
1     415-555-0172
2     510-555-0183
3     510-555-0194
4     628-555-0105
5     628-555-0116
6     415-555-0127
7              NaN
8     510-555-0139
9     510-555-0140
10    628-555-0151
11    628-555-0162
12    415-555-0173
13             NaN
14    510-555-0184
15    510-555-0195
16    628-555-0106
17    628-555-0117
18    415-555-0128
19    415-555-0139
20    628-555-0151
21    510-555-0142
22    510-555-0153
23    628-555-0164
24    628-555-0175
25    415-555-0161
26    415-555-0172
27    510-555-0183
28    510-555-0194
29    628-555-0105
30    628-555-0116
31    415-555-0127
32             NaN
33    510-555-0139
34    510-555-0140
35    628-555-0151
36    628-555-0162
37    415-555-0173
38             NaN
39    510-555-0184
40    510-555-0195
41    628-555-0106
42    628-555-0117
43    415-555-0128
44    415-555-0139
45    628-555-0151
46             NaN
47    510-555-0153
48    628-555-0164
49    628-555-0175
Name: MemberPhone, dtype: str

In [39]:
df["MembershipTier"].value_counts()

MembershipTier
STANDARD    9
Basic       8
Premiun     7
Premium     6
basic       5
standard    4
BASIC       4
Standard    4
premium     3
Name: count, dtype: int64

## Fix MembershipTier
 
| Step | Code | Description |
|------|------|-------------|
| 1 | `correct_word = {...}` | Dictionary mapping misspelled values to their correct spelling (`"Premiun"` → `"Premium"`) |
| 2 | `.astype(str)` | Converts the `MembershipTier` column to string type to allow string operations |
| 3 | `.str.replace(correct_word)` | Replaces the misspelled values using the correction dictionary |
| 4 | `.str.title()` | Standardizes capitalization (e.g., `"premium"` → `"Premium"`) |
| 5 | `.value_counts()` | Displays the count of each unique membership tier to verify the cleaning |
 
## Result
 
- Fixes the typo `"Premiun"` → `"Premium"`
- All tier names are normalized to Title Case
- Final value counts confirm the cleaned categories

In [40]:
correct_word = {
    "Premiun" : "Premium"
}

df["MembershipTier"] = df["MembershipTier"].astype(str).str.replace(correct_word).str.title()
df["MembershipTier"].value_counts()

MembershipTier
Basic       17
Standard    17
Premium     16
Name: count, dtype: int64

In [41]:
df["Branch"].value_counts()

Branch
riverside hub    9
Riverside Hub    8
UPTOWN HUB       8
Downtown Hub     7
downtown hub     6
Uptown Hub       6
DOWNTOWN HUB     4
Uptown Hub       2
Name: count, dtype: int64

In [42]:
df["Branch"] = df["Branch"].astype(str).str.strip().str.title()
df["Branch"].unique()

<ArrowStringArray>
['Downtown Hub', 'Riverside Hub', 'Uptown Hub']
Length: 3, dtype: str

In [43]:
df["BookingDate"] = pd.to_datetime(df["BookingDate"], format='mixed', errors='coerce')
df["BookingDate"]

0    2024-06-01
1    2024-06-02
2    2024-06-03
3    2024-06-04
4    2024-06-05
5    2024-06-06
6    2024-06-07
7    2024-06-08
8    2024-06-09
9    2024-06-10
10   2024-06-11
11   2024-06-12
12   2024-06-13
13   2024-06-14
14   2024-06-15
15   2024-06-16
16   2024-06-17
17   2024-06-18
18   2024-06-19
19   2024-06-20
20   2024-06-21
21   2024-06-22
22   2024-06-23
23   2024-06-24
24   2024-06-25
25   2024-06-26
26   2024-06-27
27   2024-06-28
28   2024-06-29
29   2024-06-30
30   2024-07-01
31   2024-07-02
32   2024-07-03
33   2024-07-04
34   2024-07-05
35   2024-07-06
36   2024-07-07
37   2024-07-08
38   2024-07-09
39   2024-07-10
40   2024-07-11
41   2024-07-12
42   2024-07-13
43   2024-07-14
44   2024-07-15
45   2024-07-16
46   2024-06-06
47   2024-07-18
48   2024-07-19
49   2024-07-20
Name: BookingDate, dtype: datetime64[us]

# `DeskType` Casing, Whitespace & Typo Correction

**Issue Identified:** Casing inconsistency, a double-space variant (`"Dedicated  Desk"`), and
a misspelling (`"Private Ofice"`).

**Fix Applied:** `.str.strip()` alone won't collapse an internal double space used
`.str.replace(r"\s+", " ", regex=True)` first to normalize internal whitespace, then the
usual title-case + typo map.

In [44]:
df["DeskType"].value_counts()

DeskType
hot desk           10
Private Office      9
Dedicated  Desk     8
private office      5
HOT DESK            5
Dedicated Desk      4
dedicated desk      4
Private Ofice       3
Hot Desk            2
Name: count, dtype: int64

In [45]:
df["DeskType"] = df["DeskType"].astype(str).str.strip().str.title()
df["DeskType"].value_counts()

DeskType
Hot Desk           17
Private Office     14
Dedicated Desk      8
Dedicated  Desk     8
Private Ofice       3
Name: count, dtype: int64

In [46]:
df["DeskType"] = df["DeskType"].astype(str).str.strip().str.replace(r"\s+", " ", regex=True)
desk_fix = {"Private Ofice": "Private Office"}
df["DeskType"] = df["DeskType"].replace(desk_fix)
df["DeskType"].value_counts()

DeskType
Hot Desk          17
Private Office    17
Dedicated Desk    16
Name: count, dtype: int64

In [47]:
df["CheckInMethod"].value_counts()

CheckInMethod
Key Card      9
key card      8
Front Desk    8
MOBILE APP    7
Mobile App    7
FRONT DESK    6
mobile app    3
front desk    2
Name: count, dtype: int64

In [48]:
df["CheckInMethod"] = df["CheckInMethod"].astype(str).str.strip().str.title()
df["CheckInMethod"].value_counts()

CheckInMethod
Mobile App    17
Key Card      17
Front Desk    16
Name: count, dtype: int64

## `HoursBooked`: Mixed-Unit Parsing

**Issue Identified:** 
written as `"4 hrs"`, `"3h"`, a bare `"2.5"`, or `"480 min"`. One row has no value logged at
all.

**Fix Applied:** Detect the `"min"` suffix, divide by 60 when present, otherwise treat the
extracted number as already being in hours. The missing row becomes `NaN`.

In [49]:
is_minutes = df["HoursBooked"].astype(str).str.contains("min", case=False, na=False)
raw_number = df["HoursBooked"].astype(str).str.extract(r"([\d.]+)")[0].astype(float)

df["HoursBooked"] = np.where(is_minutes, raw_number / 60, raw_number)
df["HoursBooked"]

0     2.0
1     8.0
2     6.0
3     5.0
4     3.0
5     4.0
6     5.0
7     1.0
8     2.0
9     4.0
10    8.0
11    2.0
12    8.0
13    6.0
14    8.0
15    3.0
16    3.0
17    6.0
18    4.0
19    8.0
20    1.0
21    8.0
22    6.0
23    4.0
24    2.0
25    1.0
26    8.0
27    4.0
28    8.0
29    3.0
30    6.0
31    6.0
32    8.0
33    6.0
34    2.0
35    8.0
36    2.0
37    1.0
38    1.0
39    4.0
40    NaN
41    5.0
42    6.0
43    3.0
44    5.0
45    6.0
46    8.0
47    2.0
48    4.0
49    3.0
Name: HoursBooked, dtype: float64

In [50]:
df["AmenitiesUsed"] = df["AmenitiesUsed"].fillna("None")
df["AmenitiesUsed"]

0                                   None
1                            Phone Booth
2       Whiteboard, Locker, Meeting Room
3                                   None
4            Whiteboard, Printer, Coffee
5           Phone Booth, Printer, Coffee
6                Locker, Printer, Coffee
7                                   None
8                                   None
9                                   None
10                                  None
11                            Whiteboard
12                           Phone Booth
13                                Locker
14                   Printer, Whiteboard
15                   Whiteboard, Printer
16                               Printer
17                                Locker
18                    Coffee, Whiteboard
19                               Printer
20                                  None
21    Printer, Meeting Room, Phone Booth
22                   Whiteboard, Printer
23                                  None
24                                  None
25                           Phone Booth
26                          Meeting Room
27               Locker, Printer, Coffee
28      Meeting Room, Locker, Whiteboard
29          Phone Booth, Printer, Coffee
30                                  None
31                                  None
32                               Printer
33                                  None
34                                Coffee
35                                  None
36                                  None
37                                Locker
38                                Coffee
39           Printer, Coffee, Whiteboard
40     Meeting Room, Printer, Whiteboard
41                           Phone Booth
42                    Whiteboard, Locker
43             Meeting Room, Phone Booth
44                            Whiteboard
45                                Coffee
46                           Phone Booth
47      Whiteboard, Meeting Room, Locker
48                                Locker
49            Coffee, Whiteboard, Locker
Name: AmenitiesUsed, dtype: str

In [51]:
df["Rating"].value_counts()

Rating
5 stars    9
4/5        9
5          9
4          8
5/5        4
3/5        4
4 stars    4
3          2
3 stars    1
Name: count, dtype: int64

In [52]:
df["Rating"] = df["Rating"].astype(str).str.extract(r"^(\d+)")[0].astype(int)
df["Rating"].value_counts()

Rating
5    22
4    21
3     7
Name: count, dtype: int64

In [53]:
df["PaymentStatus"].value_counts()

PaymentStatus
Paid       17
paid       11
PAID       10
pending     4
overdue     3
PENDING     2
OVERDUE     2
Pending     1
Name: count, dtype: int64

In [55]:
df["PaymentStatus"] = df["PaymentStatus"].astype(str).str.title()
df["PaymentStatus"].value_counts()

PaymentStatus
Paid       38
Pending     7
Overdue     5
Name: count, dtype: int64

In [56]:
df["AmountBilled"] = pd.to_numeric(df["AmountBilled"], errors = 'coerce')
df["AmountBilled"]

0      16.0
1      48.0
2      24.0
3      40.0
4      18.0
5      16.0
6      40.0
7       6.0
8     999.0
9      32.0
10     48.0
11      8.0
12     64.0
13     36.0
14     32.0
15     24.0
16     18.0
17     24.0
18     32.0
19     48.0
20      4.0
21     64.0
22     36.0
23     16.0
24     16.0
25      6.0
26     32.0
27     32.0
28     48.0
29     12.0
30     48.0
31     36.0
32     32.0
33     48.0
34     12.0
35     32.0
36     16.0
37      6.0
38      4.0
39     32.0
40      0.0
41     20.0
42     48.0
43     18.0
44     20.0
45     48.0
46     48.0
47      8.0
48     32.0
49     18.0
Name: AmountBilled, dtype: float64

# Duplicates

In [58]:
dup_cols = ["MemberName", "BookingDate", "DeskType"]
df[df.duplicated(subset=dup_cols, keep=False)]

,BookingID,MemberName,MemberEmail,MemberPhone,MembershipTier,Branch,BookingDate,DeskType,CheckInMethod,HoursBooked,AmenitiesUsed,Rating,PaymentStatus,AmountBilled,Notes
5,B006,Ezra Lindqvist,NaN,628-555-0116,Premium,Uptown Hub,2024-06-06,Private Office,Front Desk,4.0,"Phone Booth, Printer, Coffee",4,Paid,16.0,NaN
46,B047,Ezra Lindqvist,winifred.asplund@mail.com,NaN,Standard,Riverside Hub,2024-06-06,Private Office,Key Card,8.0,Phone Booth,3,Paid,48.0,NaN

In [59]:
df["MemberName"].value_counts()

MemberName
Selin Kaya           4
Ezra Lindqvist       3
Talia Bregman        2
Desmond Okafor       2
Rosalind Fenwick     2
Kwame Asante         2
Viola Marchetti      2
Priyanka Deshmukh    2
Hugo Santoro         2
Amara Chukwu         2
Bertrand Okoye       2
Marcus Feldman       2
Odalys Quintero      2
Nikolai Petrenko     2
Fatima Al-Sayed      2
Gideon Westbrook     2
Camille Duvalier     2
Tobias Reinholt      2
Aiyana Whitehorse    2
Rafael Contreras     2
Idris Mwangi         2
Noor Hendricks       2
Callista Reyes       2
Winifred Asplund     1
Name: count, dtype: int64

In [60]:
df.loc[df["MemberName"] == "Ezra Lindqvist", ["BookingID", "BookingDate", "DeskType"]]

   BookingID BookingDate        DeskType
5       B006  2024-06-06  Private Office
30      B031  2024-07-01        Hot Desk
46      B047  2024-06-06  Private Office

In [61]:
df.loc[df["MemberName"] == "Selin Kaya", ["BookingID", "BookingDate", "DeskType"]]

   BookingID BookingDate        DeskType
10      B011  2024-06-11  Dedicated Desk
20      B021  2024-06-21  Private Office
35      B036  2024-07-06  Private Office
45      B046  2024-07-16        Hot Desk

In [62]:
dupes = df[df.duplicated(subset=dup_cols, keep=False)]
drop_idx = dupes[dupes["MemberPhone"].isna()].index
df = df.drop(index= drop_idx).reset_index(drop=True)

In [63]:
df = df.merge(rates, on= "MembershipTier", how ="left")
df[["BookingID", "MembershipTier", "HourlyRate"]].head(8)

  BookingID MembershipTier  HourlyRate
0      B001          Basic           8
1      B002       Standard           6
2      B003        Premium           4
3      B004          Basic           8
4      B005       Standard           6
5      B006        Premium           4
6      B007          Basic           8
7      B008       Standard           6

In [64]:
df["HourlyRate"].isna().sum()

np.int64(0)

In [67]:
df["Correct_Bill"] = (df["HoursBooked"] * df["HourlyRate"]).round(2)
amount_mismatch = (df["AmountBilled"] - df["Correct_Bill"]).abs() > 0.01

df.loc[amount_mismatch, ["BookingID", "MembershipTier", "HoursBooked", "HourlyRate", "AmountBilled"]]

  BookingID MembershipTier  HoursBooked  HourlyRate  AmountBilled
8      B009        Premium          2.0           4         999.0

In [69]:
df["AmountBilled"] = df["Correct_Bill"].fillna(df["AmountBilled"])
df["AmountBilled"]

0     16.0
1     48.0
2     24.0
3     40.0
4     18.0
5     16.0
6     40.0
7      6.0
8      8.0
9     32.0
10    48.0
11     8.0
12    64.0
13    36.0
14    32.0
15    24.0
16    18.0
17    24.0
18    32.0
19    48.0
20     4.0
21    64.0
22    36.0
23    16.0
24    16.0
25     6.0
26    32.0
27    32.0
28    48.0
29    12.0
30    48.0
31    36.0
32    32.0
33    48.0
34    12.0
35    32.0
36    16.0
37     6.0
38     4.0
39    32.0
40     0.0
41    20.0
42    48.0
43    18.0
44    20.0
45    48.0
46     8.0
47    32.0
48    18.0
Name: AmountBilled, dtype: float64

In [70]:
df.loc[df["BookingID"] == "B009", "Notes"] = "AmountBilled does not match HoursBooked x rate - updated price"

In [71]:
df.loc[df["HoursBooked"].isna(), ["BookingID", "HoursBooked", "AmountBilled", "Notes"]]

   BookingID  HoursBooked  AmountBilled                              Notes
40      B041          NaN           0.0  Hours not logged, billing pending

In [72]:
df.loc[df["Notes"] == "Duplicate?", ["BookingID", "MemberName", "BookingDate", "DeskType"]]

   BookingID    MemberName BookingDate        DeskType
22      B023  Idris Mwangi  2024-06-23  Dedicated Desk

In [74]:
df.loc[df["MemberName"] == "Idris Mwangi", ["BookingID", "BookingDate","HoursBooked", "AmountBilled", "Notes"]]

   BookingID BookingDate  HoursBooked  AmountBilled       Notes
22      B023  2024-06-23          6.0          36.0  Duplicate?
46      B048  2024-07-18          2.0           8.0         NaN