In [57]:
import pandas as pd
import numpy as np
import re

In [58]:
df = pd.read_csv(r"C:\Users\Junayed\pandas_prac\youtube\ai_channels.csv")

In [59]:
df.head(5)

,keyword,channel_name,handle,channel_url,subscribers,n_videos,avg_views_last10,total_likes_last10,total_comments_last10,engagement_rate,is_verified,email,region,keyword_matches,matched_keywords
0,AI video,Youri van Hofwegen,Yourivanhofwegen,https://www.youtube.com/@Yourivanhofwegen,317000,10,31200,0,223,0.0984,True,NaN,United Kingdom,42,AI 3D animation | AI UGC | AI VFX | AI YouTube...
1,AI video,Dan Kieft,Dankieft,https://www.youtube.com/@Dankieft,288000,10,75300,0,799,0.2615,True,business@dankieft.com,NaN,37,AI 3D animation | AI UGC | AI VFX | AI ad crea...
2,AI video,Roboverse,roboverse987,https://www.youtube.com/@roboverse987,134000,10,17400,0,113,0.1299,False,NaN,United States,33,AI 3D animation | AI ASMR | AI UGC | AI ad cre...
3,AI video,Learn AI with Ritika,LearnAIwithRitika,https://www.youtube.com/@LearnAIwithRitika,336000,10,139800,37743,17009,0.4161,False,NaN,India,29,AI 3D animation | AI YouTube channel | AI anim...
4,AI generated video,Kevin Stratvert,KevinStratvert,https://www.youtube.com/@KevinStratvert,4410000,10,30960,6112,274,0.0070,True,NaN,United States,24,AI art tutorial | AI automation | AI avatar vi...

In [60]:
df.shape

(510, 15)

In [61]:
drop_col = ["keyword", "channel_name", "n_videos", "is_verified", "keyword_matches", "matched_keywords"]
df = df.drop(drop_col, axis=1)

In [62]:
df.head(5)

,handle,channel_url,subscribers,avg_views_last10,total_likes_last10,total_comments_last10,engagement_rate,email,region
0,Yourivanhofwegen,https://www.youtube.com/@Yourivanhofwegen,317000,31200,0,223,0.0984,NaN,United Kingdom
1,Dankieft,https://www.youtube.com/@Dankieft,288000,75300,0,799,0.2615,business@dankieft.com,NaN
2,roboverse987,https://www.youtube.com/@roboverse987,134000,17400,0,113,0.1299,NaN,United States
3,LearnAIwithRitika,https://www.youtube.com/@LearnAIwithRitika,336000,139800,37743,17009,0.4161,NaN,India
4,KevinStratvert,https://www.youtube.com/@KevinStratvert,4410000,30960,6112,274,0.0070,NaN,United States

In [63]:
def add_at(val):
    if pd.isna(val):
        return np.nan
    return f"@{val}"

df["handle"] = df["handle"].apply(add_at)

In [64]:
df.head(5)

,handle,channel_url,subscribers,avg_views_last10,total_likes_last10,total_comments_last10,engagement_rate,email,region
0,@Yourivanhofwegen,https://www.youtube.com/@Yourivanhofwegen,317000,31200,0,223,0.0984,NaN,United Kingdom
1,@Dankieft,https://www.youtube.com/@Dankieft,288000,75300,0,799,0.2615,business@dankieft.com,NaN
2,@roboverse987,https://www.youtube.com/@roboverse987,134000,17400,0,113,0.1299,NaN,United States
3,@LearnAIwithRitika,https://www.youtube.com/@LearnAIwithRitika,336000,139800,37743,17009,0.4161,NaN,India
4,@KevinStratvert,https://www.youtube.com/@KevinStratvert,4410000,30960,6112,274,0.0070,NaN,United States

In [65]:
engagement_sum = df["total_likes_last10"] + df["total_comments_last10"]
locking = df.columns.get_loc("avg_views_last10")
df.insert(locking + 1, "Total_engagement_sum", engagement_sum)

In [66]:
df.head(5)

,handle,channel_url,subscribers,avg_views_last10,Total_engagement_sum,total_likes_last10,total_comments_last10,engagement_rate,email,region
0,@Yourivanhofwegen,https://www.youtube.com/@Yourivanhofwegen,317000,31200,223,0,223,0.0984,NaN,United Kingdom
1,@Dankieft,https://www.youtube.com/@Dankieft,288000,75300,799,0,799,0.2615,business@dankieft.com,NaN
2,@roboverse987,https://www.youtube.com/@roboverse987,134000,17400,113,0,113,0.1299,NaN,United States
3,@LearnAIwithRitika,https://www.youtube.com/@LearnAIwithRitika,336000,139800,54752,37743,17009,0.4161,NaN,India
4,@KevinStratvert,https://www.youtube.com/@KevinStratvert,4410000,30960,6386,6112,274,0.0070,NaN,United States

In [67]:
drop_col1 = ["total_likes_last10", "total_comments_last10"]
df = df.drop(drop_col1, axis=1)
df.head(5)

,handle,channel_url,subscribers,avg_views_last10,Total_engagement_sum,engagement_rate,email,region
0,@Yourivanhofwegen,https://www.youtube.com/@Yourivanhofwegen,317000,31200,223,0.0984,NaN,United Kingdom
1,@Dankieft,https://www.youtube.com/@Dankieft,288000,75300,799,0.2615,business@dankieft.com,NaN
2,@roboverse987,https://www.youtube.com/@roboverse987,134000,17400,113,0.1299,NaN,United States
3,@LearnAIwithRitika,https://www.youtube.com/@LearnAIwithRitika,336000,139800,54752,0.4161,NaN,India
4,@KevinStratvert,https://www.youtube.com/@KevinStratvert,4410000,30960,6386,0.0070,NaN,United States

In [68]:
sorted_country = ["United States", "India", "Canada", "Indonesia", "Philippines"]

df = df[df["region"].isin(sorted_country)]

In [69]:
df["region"].value_counts()

region
United States    191
India            100
Canada            15
Indonesia          2
Philippines        1
Name: count, dtype: int64

In [70]:
df.to_excel("cleaned_ai_channels.xlsx", index=False)

In [71]:
df["email"].count()

np.int64(137)

In [74]:
dup_cols = ["handle", "email", "region"]
df[df.duplicated(subset=dup_cols, keep=False)]

Empty DataFrame
Columns: [handle, channel_url, subscribers, avg_views_last10, Total_engagement_sum, engagement_rate, email, region]
Index: []

In [72]:
df["email"].value_counts()

email
arvindzoneofficial@gmail.com     2
hello@gener8tive.ai              1
piyushkumarsoni8409@gmail.com    1
collabraj@gmail.com              1
creatorsearch89@gmail.com        1
                                ..
krishnadhakpade788@gmail.com     1
testtutorials391@gmail.com.      1
howtocado@gmail.com              1
awalaloot@gmail.com              1
drissiyassin40@gmail.com         1
Name: count, Length: 136, dtype: int64